Issue #98 Known issues of AdGuard for Windows
AdguardTeam/KnowledgeBase pull request #116
Opened 2023-01-30 11:28 UTC by anastasiia-fedotova

AdGuard for Windows and AdGuard VPN for Windows compatibility issues

2023-01-30 13:24 UTC, adbuker requested changes

2023-01-30 13:24 UTC, adbuker commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +However, in some cases there may be problems. If you have both apps enabled and the *Use redirect driver mode* setting is **activated** in AdGuard Ad Blocker, then traffic filtering doesn’t work. The
ну вот тут не совсем правильно. Точнее не правильно. тут не `in some cases`,а в 100% случаев. Эти галочки должны быть именно как описано, только в этих условиях будет работать.

2023-01-30 13:24 UTC, adbuker commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +Once you install AdGuard for Windows and AdGuard VPN for Windows, they just start working together. Such 100% compatibility between the two apps is possible thanks to the unique AdGuard VPN protocol,
тут тоже весьма спорная формулировка - откуда она? дело в том, что компатибилити как минимум на винде зависят в большей степени от реализации, а не от протокола

2023-01-30 13:24 UTC, adbuker commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +However, in some cases there may be problems. If you have both apps enabled and the *Use redirect driver mode* setting is **activated** in AdGuard Ad Blocker, then traffic filtering doesn’t work. The
>The same will happen if the *Filter localhost* setting is **disabled**.

так не получится, ибо бы вырубаем возможность изменения настройки, когда у нас включен ВПН. Либо ты поставь у себя 2 продукта, либо я тебе покажу удалённо - просто лучше 1 раз увидеть

2023-01-30 13:24 UTC, adbuker commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +As a temporary solution to the problem with AdGuard filtering in this case, we suggest returning settings to the default state, i.e. disable the *Use redirect driver mode* and enable the *Filter loca
не совсем понял, про какую проблему ты говоришь и почему именно "темпоралили солюшен"?

2023-01-31 12:56 UTC, anastasiia-fedotova commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +However, in some cases there may be problems. If you have both apps enabled and the *Use redirect driver mode* setting is **activated** in AdGuard Ad Blocker, then traffic filtering doesn’t work. The
1. in some cases - тут относится к предыдущему абзацу. типа приложения работают друг с другом идеально. но в некоторых случаях что-то идет не так. например, ...

2. Я видела задизейбленную галку. Но ведь можно отключить впн и поменять настройку адича?

2023-01-31 12:59 UTC, anastasiia-fedotova commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +Once you install AdGuard for Windows and AdGuard VPN for Windows, they just start working together. Such 100% compatibility between the two apps is possible thanks to the unique AdGuard VPN protocol,
блин, значит, это я неправильно воспользовалась своими знаниями. Короче, этот заход удаляем.

2023-01-31 13:00 UTC, anastasiia-fedotova commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +As a temporary solution to the problem with AdGuard filtering in this case, we suggest returning settings to the default state, i.e. disable the *Use redirect driver mode* and enable the *Filter loca
я говорю про проблему с фильтрацией. типа если сменить дефолтные настройки, то перестает работать фильтрация в Адгард. Ну а темпорари - пушто ты ж сказал, что в какой-то версии вы этот момент поправите.

2023-02-06 22:59 UTC, adbuker requested changes

2023-02-06 22:59 UTC, adbuker commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +> Usually changing these settings default state is required to overcome issues related to the simultaneous operation of AdGuard Ad Blocker and various apps working with the network (e.g. antiviruses,
тут не только Ad Blocker

2023-02-06 22:59 UTC, adbuker commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +> Usually changing these settings default state is required to overcome issues related to the simultaneous operation of AdGuard Ad Blocker and various apps working with the network (e.g. antiviruses,
ну тут как бы возникает вопрос - мы пишем, что менять нельзя, но иногда изменения необходимы для компатибилити. С одной стороны ничего не добавить, но с другой стороны можно дополнительно указать, что мол такие редкие случаи мы будем рады рассмотреть отдельно, пишите таски (ссылка на гх).

2023-02-06 22:59 UTC, adbuker commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +We are currently working on a solution to this problem.
`solution to this problem.` - немного относится к предыдущему комментарию, давай напишем это в формате выше

2023-02-08 08:43 UTC, el-termikael requested changes

2023-02-08 08:43 UTC, el-termikael commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +There are two specific settings in AdGuard for Windows: *Use redirect driver mode* and *Filter localhost*. By default, the *Use redirect driver mode* setting is disabled and the *Filter localhost* –
```suggestion
There are two specific settings in AdGuard for Windows: *Use redirect driver mode* and *Filter localhost*. By default, the first one is disabled and the latter one is enabled. Changing any of these settings will inevitably disrupt AdGuard's filtering if both AdGuard Ad Blocker and AdGuard VPN are enabled on your device.  
```

2023-02-08 08:43 UTC, el-termikael commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +Usually changing these settings default state is required to overcome issues related to the simultaneous operation of AdGuard Ad Blocker and various apps working with the network (e.g. antiviruses, V
```suggestion
Changing these settings is only required to overcome issues related to the simultaneous operation of AdGuard Ad Blocker and apps working on the network level (e.g. antiviruses, VPNs, network filters, etc). If you come across a situation where you need AdGuard Ad Blocker and AdGuard VPN to work simultaneously and correctly, and the default state of the above settings needs to be changed — [create an issue on GitHub](https://github.com/AdguardTeam/AdguardForWindows/issues/new/choose) so we can help you personally.
```

2023-02-08 08:43 UTC, el-termikael commented on docs/adguard-for-windows/solving-problems/known-issues.md
> +We are currently working towards overcoming the listrd above limitations of simultaneous work of our applications.
```suggestion
We are currently working on overcoming the above-listed limitations of the simultaneous work of our apps. 
```

2023-02-08 09:20 UTC, adbuker approved these changes

2023-02-08 10:06 UTC, el-termikael approved these changes

2023-02-09 10:41 UTC, merged