Added content for AdGuard for Safari
AdguardTeam/KnowledgeBase pull request #14
Opened 2022-08-17 07:26 UTC by ss-orlova

2022-09-06 14:31 UTC, ameshkov requested changes

2022-09-06 14:31 UTC, ameshkov commented on docs/adguard-browser-extension/features-overview.md
> -AdGuard provides a range of software products that block ads and trackers on different platforms. One of the most popular AdGuard products is a free extension that works in five popular browsers: Chr
Вместо того, чтобы портить статьи и потом иметь битые ссылки вы должны создать заглушки для статей и иметь нормальные ссылки.

2022-09-13 15:17 UTC, ameshkov approved these changes

2022-09-13 15:23 UTC, vbagirov requested changes

2022-09-13 15:23 UTC, vbagirov commented on docs/adguard-for-safari/installation.md
> +sidebar-position: 2
было правильно, с `_`

2022-09-13 15:23 UTC, vbagirov commented on docs/adguard-for-safari/overview.md
> +### AdGuard General {#general}
у тебя два анкора с одинаковым названием

2022-09-13 15:23 UTC, vbagirov commented on docs/adguard-for-safari/overview.md
> +> Reminder: AdGuard for Safari can be downloaded for free [from the App Store](https://apps.apple.com/en/app/adguard-for-safari/id1440147259). A detailed setup instruction is available in the [Knowle
лучше на такую поменять
```https://apps.apple.com/app/adguard-for-safari/id1440147259```

2022-09-13 16:32 UTC, vbagirov approved these changes

2022-09-15 10:40 UTC, merged