Add article about Tor filtering
AdguardTeam/KnowledgeBase pull request #143
Opened 2023-02-27 16:37 UTC by ss-orlova

2023-02-27 16:42 UTC, vozersky commented on docs/adguard-for-mac/solving-problems/tor-filtering.md
> +If you decide to to filter Tor and check its box in *Preferences* → *Network* → *Applications*, AdGuard will show you this dialog window:
"to to"

2023-02-27 16:42 UTC, vozersky commented on docs/adguard-for-mac/solving-problems/tor-filtering.md
> +By updating Tor setting, AdGuard will set the following:
settings

2023-02-27 17:12 UTC, vozersky approved these changes

2023-02-28 07:26 UTC, el-termikael requested changes

2023-02-28 07:26 UTC, el-termikael commented on docs/adguard-for-mac/solving-problems/tor-filtering.md
> +If you decide to filter Tor and check its box in *Preferences* → *Network* → *Applications*, AdGuard will show you this dialog window:
dialog box

2023-02-28 07:26 UTC, el-termikael commented on docs/adguard-for-mac/solving-problems/tor-filtering.md
> +[AdGuard dialog window](https://cdn.adtidy.org/content/kb/ad_blocker/mac/tor-setup.png)
и тут

2023-02-28 07:26 UTC, el-termikael commented on docs/adguard-for-mac/solving-problems/tor-filtering.md
> +By default, Tor Browser is added to AdGuard’s list of filtered applications. However, to filter it, AdGuard needs to change Tor's security settings. This will make Tor trust AdGuard's CA certificate.
I guess, it's Tor or the Tor Browser

2023-02-28 09:17 UTC, el-termikael approved these changes

2023-02-28 09:22 UTC, merged