Update License section due to new account release
AdguardTeam/KnowledgeBase pull request #156
Opened 2023-03-20 14:37 UTC by vyanovsky

Update License section in accordance with new AdGuard account release, some navigation changes (added 2 new articles while rearranging content between articles), added new account screenshots

2023-03-20 15:13 UTC, el-termikael requested changes

2023-03-20 15:13 UTC, el-termikael commented on docs/general/license/cancel-refund.md
> +* purchased the license more than 60 days ago,
a license here and below

2023-03-20 15:13 UTC, el-termikael commented on docs/general/license/cancel-refund.md
> +* purchaded the license by a distributor,
```suggestion
* purchased the license from a distributor,
```

2023-03-20 15:13 UTC, el-termikael commented on docs/general/license/cancel-refund.md
> +* applied for a partial refund for license key upgrade or prolongation.
```suggestion
* applied for a partial refund for a license key upgrade or renewal.
```

2023-03-20 15:13 UTC, el-termikael commented on docs/general/license/payment-options.md
> +  * purchasing another license on the official websites of AdGuard products,
это же кб блокировщика, здесь достаточно упомянуть сайт этого продукта

2023-03-20 15:13 UTC, el-termikael commented on docs/general/license/transfer.md
> +There's three ways in which you can do it:
```suggestion
There are three ways to do it:
```

2023-03-20 15:13 UTC, el-termikael commented on docs/general/license/transfer.md
> +
лишняя пустая строка

2023-03-20 15:13 UTC, el-termikael commented on docs/general/license/transfer.md
> + 2. Go to **Licenses** tab in the menu
```suggestion
 2. Go to the **Licenses** tab
```

2023-03-20 15:13 UTC, el-termikael commented on docs/general/license/transfer.md
> + 4. Click **Unbind** (**IMPORTANT**: be sure to note/remember the license key)
we should abstain from using caps lock for typing important/warning and other alarm messages

2023-03-20 15:25 UTC, vyanovsky commented on docs/general/license/cancel-refund.md
> + 3. Find the subscription you want to cancel, and click **Cancel subscription**
Тогда с under (cм. скрин https://cdn.adtidy.org/content/kb/ad_blocker/general/newaccount-cancel-sub.png)

Click **Cancel subscription** under the subscription you no longer need

2023-03-20 15:28 UTC, vyanovsky commented on docs/general/license/cancel-refund.md
> +A refund may be denied if you:
Decline or deny

2023-03-20 15:34 UTC, vyanovsky commented on docs/general/license/payment-options.md
> +  * purchasing another license on the official websites of AdGuard products,
согласен, не я писал)

2023-03-20 15:42 UTC, vyanovsky commented on docs/general/license/cancel-refund.md
> +A refund may be denied if you:
I think declined is nice

2023-03-21 06:58 UTC, vbagirov requested changes

2023-03-21 06:58 UTC, vbagirov commented on docs/general/license/transfer.md
> +  * by clicking the *Reset license* button (applies to desktop apps)
я бы уточнил более прямым текстом что это внутри приложения

2023-03-21 06:58 UTC, vbagirov commented on docs/general/license/transfer.md
> +     2. In the license card, click the device you want to unbind
Если я правильно понимаю, на десктопе иначе выглядит всё. Будем как-то это учитывать? И вообще, точно по дефолту мы ставим скрины из мобильной версии?

2023-03-21 06:58 UTC, vbagirov commented on docs/general/license/transfer.md
> + 1. Go to the first AdGuard account
По-моему, неочевидно, что такое first. Лучше написать типа "в аккаунт с активной лицензией, которую вы хотите переместить"

2023-03-21 06:58 UTC, vbagirov commented on docs/general/license/transfer.md
> + 4. Go to the second AdGuard account
аналогично

2023-03-21 06:58 UTC, vbagirov commented on docs/general/license/transfer.md
> + 6. Click **Bind license** in the upper right corner
в десктопе кнопка называется "Add a license"

2023-03-21 06:58 UTC, vbagirov commented on docs/general/license/payment-options.md
> +1. To increase the functionality of your AdGuard products, you can **upgrade your free or trial license to the full version**.
Чтобы пункты не "висели в воздухе", я бы перед этим написал фразу в духе "Это может быть полезно в следующих случаях:" или что-то такое

2023-03-21 06:58 UTC, vbagirov commented on docs/general/license/payment-options.md
> +3. You can also **upgrade your subscription to a Lifetime license**.
А это мне кажется не совсем подходит как ещё один пункт списка, я бы лучше это просто через отступ отдельной строкой без списка сделал.

2023-03-21 06:58 UTC, vbagirov commented on docs/general/license/payment-options.md
> +  * clicking the *Upgrade to Lifetime* and/or *Increase device limit* in your AdGuard account:
Опять же, на десктопе всё выглядит иначе и кнопки другие

2023-03-21 07:06 UTC, vyanovsky commented on docs/general/license/transfer.md
> +     2. In the license card, click the device you want to unbind
не, на декстопе по сути так же, слева меню и в нем выбираешь AdGuard Ad Blocker

я когда делал сркины туда сюда стягивал сравнивал моб и десктоп версию, чтобы сделать скрин который юзеру поможет в обоих случаях

2023-03-21 07:10 UTC, vyanovsky commented on docs/general/license/transfer.md
> + 6. Click **Bind license** in the upper right corner
не. смотри новый аккаунт

<img width="1213" alt="Valery r31a5" src="https://user-images.githubusercontent.com/51786050/226538770-edee658b-4dc6-4308-aa8b-75e7c07b0716.png">

2023-03-21 08:43 UTC, vyanovsky commented on docs/general/license/payment-options.md
> +1. To increase the functionality of your AdGuard products, you can **upgrade your free or trial license to the full version**.
ммм, может вот так переписать?

To make it more convenient to use your AdGuard products, you can upgrade your license.
----->
To make more use of AdGuard products, you might want to upgrade your license for following benefits:

2023-03-21 08:46 UTC, vyanovsky commented on docs/general/license/payment-options.md
> +## How to purchase a license{#purchase}
да, например в статье what-is они так прописаны - на продовой кб работает

2023-03-21 08:47 UTC, vyanovsky commented on docs/general/license/transfer.md
> + 1. Go to the first AdGuard account
думал над этим, но в итоге какая-то сложная вычурная фраза получается, которую в итоге все равно сложно понять

есть идеи формулировки хорошей?

2023-03-21 08:51 UTC, vyanovsky commented on docs/general/license/payment-options.md
> +1. To increase the functionality of your AdGuard products, you can **upgrade your free or trial license to the full version**.
как насчет вот так

To make it more convenient to use your AdGuard products, you can upgrade your license.
---->
To make more use of your AdGuard products, you might want to upgrade your license for following benefits:

2023-03-21 08:56 UTC, vbagirov commented on docs/general/license/transfer.md
> + 1. Go to the first AdGuard account
Я бы написал так, мне кажется сравнительно ок для восприятия:

Go to your AdGuard account that contains the license you would like to transfer

2023-03-21 08:59 UTC, vbagirov commented on docs/general/license/payment-options.md
> +1. To increase the functionality of your AdGuard products, you can **upgrade your free or trial license to the full version**.
Фраза хорошая, но тогда сами пункты тоже надо будет переформулировать

2023-03-21 09:00 UTC, vbagirov commented on docs/general/license/payment-options.md
> +3. You can also **upgrade your subscription to a Lifetime license**.
Тогда может слово сабскрипшн тут не использовать, если везде до этого было license?

2023-03-21 09:12 UTC, el-termikael commented on docs/general/license/cancel-refund.md
> + 3. Click **Cancel subscription** under the subscription you no longer need
under —> below

2023-03-21 09:30 UTC, vyanovsky commented on docs/general/license/payment-options.md
> +1. To increase the functionality of your AdGuard products, you can **upgrade your free or trial license to the full version**.
итог:

To make more use of your AdGuard products, you can upgrade your license for following benefits.

1. To increase the functionality of your AdGuard products, you can **upgrade your free or trial license to the full version**.
2. To extend the number of devices, you can **upgrade your Personal license to a Family one**.
3. You can also **upgrade your [subscription](../what-is) to a Lifetime license**.

2023-03-21 10:53 UTC, vbagirov approved these changes

2023-03-22 08:36 UTC, el-termikael commented on docs/general/license/payment-options.md
> +To make more use of your AdGuard products, you can upgrade your license for following benefits.
```suggestion
To make more use of your AdGuard products, you can upgrade your license for the following benefits.
```

2023-04-06 06:46 UTC, merged