Updated AdGuard for Windows Advanced Settings guide
AdguardTeam/KnowledgeBase pull request #158
Opened 2023-03-22 20:09 UTC by anastasiia-fedotova

new settings added from v7.13 beta

2023-03-22 21:22 UTC, sfionov commented
Кстати `Action applied to blocked DNS requests` ([link](https://github.com/AdguardTeam/KnowledgeBase/pull/158/files#diff-21d749cab16b6b5e7279bd7921297555881ac9ba8e50a45de87a3e488c5bdb87R134)) в следующей бете станет двумя отдельными опциями - 
`Blocking mode for adblock-style rules` и `Blocking mode for hosts rules`

2023-03-22 21:23 UTC, sfionov commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +### Use HTTP/3 for DNS-over-HTTPS
Мне кажется, описания этих опций стоит поместить после "Custom IPv4/IPv6 address"

Ранее в 66-й строке был вариант "Reply with custom IP address", и двумя строками ниже уже описание этих опций. Теперь они разорваны :(

2023-03-23 15:09 UTC, el-termikael requested changes

2023-03-23 15:09 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +
лишняя пустая строка

2023-03-23 15:09 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +If address resolving failed on each of the forwarded upstreams, as well as on the fallback domains, then the response to the dns request will be SERVFAIL.
DNS request
`SERVFAIL`

2023-03-24 11:42 UTC, anastasiia-fedotova commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +### Show AdGuard VPN in Settings
да, с большой

2023-03-24 11:43 UTC, anastasiia-fedotova commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +If you have AdGuard VPN for Windows on your computer, activate this feature to open AdGuard VPN or visit its website from the AdGuard app.
так и есть

2023-03-24 11:45 UTC, anastasiia-fedotova commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +If the verification takes too long, AdGuard will establish a connection and continue checking in the background. If the certificate is revoked, the current and future connections to the domain will b
не поняла. ты хочешь так:
If the certificate is revoked, and current and future connections to the domain will be blocked.

2023-03-24 13:07 UTC, anastasiia-fedotova commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +Starting from v7.12, by default, AdGuard for Windows does not filter traffic after auto-start on OS startup if the option *Launch AdGuard at system start-up* is disabled. In other words, the AdGuard
Слушай, я так понимаю, что не надо убирать ни "on OS startup", ни "service". @adbuker , вопрос к тебе

2023-03-24 13:20 UTC, anastasiia-fedotova commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +If you want AdGuard not to filter particular subnets, you should enable this feature and specify the IP ranges in the CIDR notation (e.g. 98.51.100.14/24) at the **IP ranges excluded from filtering**
доне

2023-03-24 13:23 UTC, anastasiia-fedotova commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +Previously known as low-level settings, Advanced Settings mostly contain settings that go beyond the average user's competence and don't have application in everyday use. AdGuard for Windows is desig
доне

2023-03-27 07:03 UTC, adbuker commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +If you have AdGuard VPN for Windows on your computer, activate this feature to open AdGuard VPN or visit its website from the AdGuard app.
>to open AdGuard VPN or visit its website from the AdGuard app.

на самом деле тут тоже круто бы исправить - суть в том, что у нас есть несколько "вкладок" настроек. Одна из них - есть ["вкладка" про впн](https://uploads.adguard.org/buker-386qx.png). Эта вкладка может быть по-умолчанию сокрыта (зависит от языка системы/приложения), но пользователь в любой момент может отобразить её

Таким образом надо написать что-то типа 
"включение данной опции позволяет отобразить вкладку AdGuard VPN в разделе "Настройки" для удобства открытия соответствующего приложений и/или посещения вебсайта"

2023-03-27 07:15 UTC, adbuker commented
> Кстати `Action applied to blocked DNS requests` ([link](https://github.com/AdguardTeam/KnowledgeBase/pull/158/files#diff-21d749cab16b6b5e7279bd7921297555881ac9ba8e50a45de87a3e488c5bdb87R134)) в следующей бете станет двумя отдельными опциями - `Blocking mode for adblock-style rules` и `Blocking mode for hosts rules`

в бете 2 еще не будет, но в следующей бете(рц) точно. Тексты есть в [пулл-реквесте](https://bit.adguard.com/projects/ADGUARD-WIN/repos/adguard-windows/pull-requests/2393/diff#adguard/Adguard.UI/Properties/Resources.resx?t=3288). По сути отличается одним словом

2023-03-27 14:19 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +If the verification takes too long, AdGuard will establish a connection and continue checking in the background. If the certificate is revoked, the current and future connections to the domain will b
тьфу, просто current хочу

2023-03-27 14:45 UTC, sfionov approved these changes

2023-03-27 14:54 UTC, el-termikael approved these changes

2023-03-29 08:15 UTC, adbuker requested changes

2023-03-29 08:15 UTC, adbuker commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +Starting from v7.12, by default, AdGuard for Windows does not filter traffic after auto-start on OS startup if the option *Launch AdGuard at system start-up* is disabled. In other words, the AdGuard
ну всё изначальный вариант был лучше, `auto-start` не нужен, как я писал

2023-03-29 08:15 UTC, adbuker commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +Starting from v7.12, by default, AdGuard for Windows does not filter traffic after auto-start on OS startup if the option *Launch AdGuard at system start-up* is disabled. In other words, the AdGuard
Starting from v7.12, by default, AdGuard's service does not filter traffic after OS startup if the option *Launch AdGuard at system start-up* is disabled. In other words, the AdGuard's service is started in “idle” mode. Enable this option to make AdGuard filter traffic even if the app is not launched.

2023-03-29 08:24 UTC, adbuker requested changes

2023-03-29 08:24 UTC, adbuker commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-windows/solving-problems/low-level-settings.md
> +*Note that before v7.12 the AdGuard service started in filtering mode by default (even if the *Launch AdGuard at system start-up” was disabled). If you were satisfied with the old behavior, enable th
AdGuard's service

2023-03-29 08:31 UTC, merged