Updated Android low-level settings guide
AdguardTeam/KnowledgeBase pull request #185
Opened 2023-04-27 08:30 UTC by anastasiia-fedotova

2023-05-14 13:48 UTC, Numci requested changes

2023-05-14 13:48 UTC, Numci commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +If enabled, AdGuard will create the special file name `timestamp>.pcap` (for instance, 1682599851461.pcap). It contains all network packets transferred through the VPN. This file is located in the ap
`timestamp>.pcap` -> `timestamp.pcap`

2023-05-15 13:50 UTC, el-termikael requested changes

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +To go to *Low-level settings*, open AdGUard and tap the gear icon on the bottom-right corner of the screen. Then choose *General → Advanced → Low-level settings*.
AdGUard

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +To go to *Low-level settings*, open AdGUard and tap the gear icon on the bottom-right corner of the screen. Then choose *General → Advanced → Low-level settings*.
on the bottom-right corner —> in the lower right corner

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +For Android v4.0 we completely redesigned the low-level settings: divided them into logic blocks, made them clearer, added validation of entered values and other safety valves, got rid of some and ad
можно подумать, что это версия андроида, лучше For AdGuard v4.0 for Android

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +For Android v4.0 we completely redesigned the low-level settings: divided them into logic blocks, made them clearer, added validation of entered values and other safety valves, got rid of some and ad
```suggestion
For AdGuard v4.0 for Android we've completely redesigned the low-level settings: divided them into thematic blocks, made them clearer, added validation of entered values and other safety valves, got rid of some settings, and added others. 
```

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +Here you can specify the fallback DNS resolver(s) to be used if the configured server is unavailable. Three options exist: *Automatic DNS*, *None*, and *Custom DNS*. If no fallback server is specifie
```suggestion
Here you can specify the fallback DNS resolver(s) to be used if the configured server is unavailable. There are three options: *Automatic DNS*, *None*, and *Custom DNS*. If no fallback server is specified, the *Automatic DNS* — the system DNS or AdGuard DNS — will be used. *None* means no fallback at all. Selecting *Custom DNS* allows you to list IPv4 and IPv6 server addresses to use as upstreams.
```

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +Here you can list domains that will be directly forwarded to the fallback upstreams if they exist.
```suggestion
Here you can list domains that will be forwarded directly to fallback upstreams if they exist.
```

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +If enabled AdGuard detects search domains and automatically forwards them to the fallback upstreams if they exist.
```suggestion
If this option is enabled, AdGuard will detect search domains and automatically forward them to fallback upstreams.
```

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +
лишняя пустая строка

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +If enabled AdGuard detects search domains and automatically forwards them to the fallback upstreams if they exist.
а, ну или в формате как ниже:
If enabled, AdGuard strips Encrypted Client Hello parameters from DNS responses.

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +If the OCSP check completes within the minimum timeout, AdGuard will immediately apply the result: block the connection if the certificate is revoked or establish a connection if the certificate is v
```suggestion
If the OCSP check is completed within the minimum timeout, AdGuard will immediately block the connection if the certificate is revoked or establish the connection if the certificate is valid. 
```

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +If the verification takes too long, AdGuard will establish a connection and continue checking in the background. If the certificate is revoked, current and future connections to the domain will be bl
```suggestion
If the verification takes too long, AdGuard will establish a connection and continue checking the certificate in the background. If it is revoked, current and future connections to the domain will be blocked.
```

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +### Outbound Proxy
proxy

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +Here can be listed package names and UIDs you want to exclude from AdGuard protection.
```suggestion
Here you can list package names and UIDs that you want to exclude from AdGuard protection.
```

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +#### QUIC bypass packages
не packets?

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +After a system defined number of unsuccessful attempts to get a response from the server, the system automatically closes the TCP connection.
system-defined number

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +Here you can enter IP address that will be used to create a TUN interface. By default, it is `2001:db8:ad:0:ff::`.
```suggestion
Here you can enter the IP address that will be used to create a TUN interface. By default, it is `2001:db8:ad:0:ff::`.
```

2023-05-15 13:50 UTC, el-termikael commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +Korean users may encounter issues with Samsung Pay when AdGuard is enabled. Activate this feature to pause AdGuards’ protection and use the Samsung Pay app seamlessly.
```suggestion
Korean users may encounter issues with Samsung Pay when AdGuard is enabled. Activate this feature to pause AdGuard's protection and use the Samsung Pay app seamlessly.
```

2023-05-16 11:18 UTC, anastasiia-fedotova commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +### Outbound Proxy
В приложении написано с большой буквы

2023-05-16 11:19 UTC, anastasiia-fedotova commented on i18n/be/docusaurus-plugin-content-docs/current/adguard-for-android/solving-problems/low-level-settings.md
> +#### QUIC bypass packages
нет

2023-05-22 14:03 UTC, el-termikael requested changes

2023-05-22 14:03 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/low-level-settings.md
> +If enabled, AdGuard will create the special file name `timestamp.pcap` (for instance, 1682599851461.pcap). It contains all network packets transferred through the VPN. This file is located in the app
можно создать файл, а не название файла
AdGuard создаст файл с расширением .pcap и таймстемпом в названии (например, `1682599851461.pcap`)
или
AdGuard создаст файл с названием формата `1682599851461.pcap`

2023-05-22 14:03 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/low-level-settings.md
> +Here you can enter IP address that will be used to create a TUN interface. By default, it is `172.18.11.218`.
```suggestion
Here you can enter the IP address that will be used to create a TUN interface. By default, it is `172.18.11.218`.
```

2023-05-23 14:07 UTC, anastasiia-fedotova commented on docs/adguard-for-android/solving-problems/low-level-settings.md
> +If you need to activate debugging of scriptlets, enable this feature. Then there will be messages in the browser log that some scriplet rules have been applied.
написано по мотивам этого пояснения от Серёжи:
ПОЯСНЕНИЕ: Включает режим дебага для scriplet-ов. В логе браузера будут видны сообщения о том, что каки-то scriplet-правила были применены.

2023-05-23 14:33 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/low-level-settings.md
> +If you need to activate debugging of scriptlets, enable this feature. Then there will be messages in the browser log that some scriplet rules have been applied.
посмотрела, "messages in the browser log" иногда говорят, можем так оставить

2023-05-23 14:34 UTC, el-termikael approved these changes

2023-05-23 14:56 UTC, Numci approved these changes

2023-05-23 14:59 UTC, merged