Add specific userscript syntax for `$extension`
AdguardTeam/KnowledgeBase pull request #197
Opened 2023-05-31 14:59 UTC by grumaxxx

2023-05-31 15:18 UTC, sfionov commented on docs/general/ad-filtering/create-own-filters.md
> +Each userscript name should be separately quoted (") and multiple userscript names should be comma separated.
Нужен пример как квотить юзерскрипт с `"` в названии

2023-05-31 16:31 UTC, grumaxxx commented on docs/general/ad-filtering/create-own-filters.md
> +Each userscript name should be separately quoted (") and multiple userscript names should be comma separated.
Добавил экранирование

2023-06-01 06:58 UTC, sxgunchenko requested changes
Не забывайте звать кого-нибудь из контентанов - обычно это @el-termikael

2023-06-01 06:58 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +$extension="userscript_name1"[,"userscript_name2"[,"userscript_name3"[...]]]
1) А зачем имена в кавычки заключать?
2) У нас уже есть паттерн для перечисления - через `|` (например, `$domain`). Может так же сделать?

2023-06-01 07:28 UTC, ameshkov requested changes

2023-06-01 07:28 UTC, ameshkov commented on docs/general/ad-filtering/create-own-filters.md
> +$extension="userscript_name1"[,"userscript_name2"[,"userscript_name3"[...]]]
Кавычки можно сделать не обязательными (если в имени юзерскрипта нет запятых например то это не принципиально).

Вообще для консистентности предлагаю сделать как тут:
https://adguard-dns.io/kb/general/dns-filtering-syntax/#client

2023-06-01 07:28 UTC, ameshkov commented on docs/general/ad-filtering/create-own-filters.md
> +$extension="userscript_name1"[,"userscript_name2"[,"userscript_name3"[...]]]
Логично будет позволить инвертировать исключение тоже:
`$extension=~userscript`

2023-06-01 07:28 UTC, grumaxxx commented
@sxgunchenko 
> Не забывайте звать кого-нибудь из контентанов - обычно это @el-termikael

Ага, не добавил сразу так как еще не финальная версия)

2023-06-01 08:15 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +$extension="userscript_name1"[,"userscript_name2"[,"userscript_name3"[...]]]
> 1. Практически во всех именах юзерскриптов пробелы

вроде это не должно мешать парсингу 🤔 но можно для наглядности и с ними оставить (или сделать необязательными, как Андрей предложил)

2023-06-01 08:17 UTC, grumaxxx commented on docs/general/ad-filtering/create-own-filters.md
> +$extension="userscript_name1"[,"userscript_name2"[,"userscript_name3"[...]]]
Ну я исходил наверное больше из наглядности да, просто будет тяжело читаемо иначе, учитывая что, как правило, они состоят из нескольких слов разделенных пробелами и скобками
+ в ДНС правилах так же)

2023-06-01 08:22 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +`userscript_name(i)` stand for specific userscripts name to be disabled by the modifier. The modifier can contain any number of userscript names or not contain them at all. In the latter case the mod
только у нас обычно совместимость примерно [так](https://github.com/AdguardTeam/KnowledgeBase/blob/master/docs/general/ad-filtering/create-own-filters.md?plain=1#L343) указывается

2023-06-01 08:24 UTC, ameshkov commented on docs/general/ad-filtering/create-own-filters.md
> +$extension="userscript_name1"[,"userscript_name2"[,"userscript_name3"[...]]]
Давайте сделаем ровно как в ДНС правилах, там поддерживается как с кавычками так и без, плюс там кавычки можно одинарные или двойные

2023-06-01 08:27 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +`userscript_name(i)` stand for specific userscripts name to be disabled by the modifier. The modifier can contain any number of userscript names or not contain them at all. In the latter case the mod
ну это как-то менее заметно - может ввести в заблуждение

но как хотите :)

2023-06-01 08:42 UTC, sxgunchenko approved these changes

2023-06-01 10:48 UTC, sfionov approved these changes

2023-06-01 10:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +`userscript_name(i)` stand for specific userscripts name to be disabled by the modifier. The modifier can contain any number of userscript names or not contain them at all. In the latter case the mod
кстати, вот, например, у стелса как указано https://github.com/AdguardTeam/KnowledgeBase/blob/master/docs/general/ad-filtering/create-own-filters.md?plain=1#L742

2023-06-01 10:58 UTC, grumaxxx commented on docs/general/ad-filtering/create-own-filters.md
> +`userscript_name(i)` stand for specific userscripts name to be disabled by the modifier. The modifier can contain any number of userscript names or not contain them at all. In the latter case the mod
Я согласен, что лучше выделить. Может @el-termikael подскажет как лучше сделать? Выделять отдельно или оставить как есть?

2023-06-01 11:33 UTC, ameshkov requested changes

2023-06-01 11:33 UTC, ameshkov commented on docs/general/ad-filtering/create-own-filters.md
> +Each userscript name should be separately quoted (") and multiple userscript names should be separated with a pipe (`|`).
Поддержи также одинарные кавычки, сделайте пожалуйста также как в днс-правилах.

2023-06-01 11:34 UTC, ameshkov requested changes
Еще чуть чуть

2023-06-01 12:16 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +`userscript_name(i)` stand for specific userscripts name to be disabled by the modifier. The modifier can contain any number of userscript names or not contain them at all. In the latter case the mod
ну вообще хорошо бы заголовок > **Compatibility with different versions of AdGuard** сделать

2023-06-01 12:23 UTC, el-termikael requested changes

2023-06-01 12:23 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +`userscript_name(i)` stand for specific userscripts name to be disabled by the modifier. The modifier can contain any number of userscript names or not contain them at all. In the latter case the mod
`userscript_name(i)` stand for specific userscripts name to be disabled by the modifier —> `userscript_name(i)` stands for a specific userscript name to be disabled by the modifier

Note that the specific userscript name is available starting with CoreLibs v1.13 — а тут, наверное имелось в виду, что отдельные имена юзерскриптов можно отключать модификатором начиная с корлибсов определённой версии?

2023-06-01 12:23 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +* `@@||example.com^$extension="AdGuard Assistant"` - disables the `AdGuard Assistant` userscript on `example.com` website.
здесь и ниже тире лишние

2023-06-01 12:27 UTC, grumaxxx commented on docs/general/ad-filtering/create-own-filters.md
> +You can also exclude userscript by adding a `~` character before the value. In this case, userscript will not be excluded.
Исключение для исключения, дефолтное поведение при добавлении - исключать. Если добавить `~`, то не будет исключен. Имелось в виду это.

2023-06-01 12:29 UTC, grumaxxx commented on docs/general/ad-filtering/create-own-filters.md
> +`userscript_name(i)` stand for specific userscripts name to be disabled by the modifier. The modifier can contain any number of userscript names or not contain them at all. In the latter case the mod
У нас сейчас упоминание с какой версии CoreLibs поддерживается что-то, находятся как попало, надо решить как мы делаем и привести к общему виду.

2023-06-01 17:06 UTC, ameshkov requested changes
Нужно добавить примеров и больше у меня вопросов не будет

2023-06-01 17:06 UTC, ameshkov commented on docs/general/ad-filtering/create-own-filters.md
> +* `@@||example.com^$extension="AdGuard Assistant"|"Popup Blocker"` disables both `AdGuard Assistant` and `Popup Blocker` userscripts on `example.com` website.
Нужны примеры с одинарными кавычками и без кавычек вообще

2023-06-02 10:56 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +You can also exclude userscript by adding a `~` character before the value. In this case, userscript will not be excluded.
может, тогда так?
You can also exclude a userscript by adding a `~` character before it. In this case, the userscript will not be disabled by the modifier.

2023-06-06 09:00 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +Userscript names usually contain spaces or other special characters, which is why you should enclose the name in quotes. Both single (`'`) and double (`"`) ASCII quotes are supported. Multiple usersc
наверно, стоит явно указать, какие имена можно оставлять без кавычек - а то сейчас сказано про все, но в действительности можно не все

2023-06-07 13:41 UTC, sxgunchenko approved these changes

2023-06-16 07:28 UTC, el-termikael approved these changes

2023-06-17 09:44 UTC, merged