Renewed the Installation article
AdguardTeam/KnowledgeBase pull request #213
Opened 2023-06-22 07:13 UTC by anastasiia-fedotova

2023-06-22 11:11 UTC, el-termikael requested changes

2023-06-22 11:11 UTC, el-termikael commented on docs/adguard-for-android/installation.md
> +A popup will then appear, prompting you to adjust *Settings*. Tap on *Settings*, navigate to *Install unknown apps*, and grant permission for the browser you've used to download the file.
```suggestion
A popup will appear. Tap *Settings*, navigate to *Install unknown apps*, and grant permission for the browser you've used to download the file.
```

2023-06-22 11:11 UTC, el-termikael commented on docs/adguard-for-android/installation.md
> +3. **Install the app**. Once the browser secures the necessary permission, the system will ask you if you want to install the AdGuard app. Tap *Install*.
```suggestion
3. **Install the app**. Once the browser has obtained the necessary permissions, the system will ask you if you want to install the AdGuard application. Tap *Install*.
```

2023-06-22 11:11 UTC, el-termikael commented on docs/adguard-for-android/installation.md
> +You will then be asked to read the *License agreement* and AdGuard's *Privacy Policy*. You can also participate in product development. To do this, you should check boxes *Send crash reports automati
```suggestion
You will then be asked to read AdGuard's *License Agreement* and *Privacy Policy*. You can also participate in product development. To do this, check the boxes for *Send crash reports automatically* and *Send technical and interaction data*. Then tap *Continue*.
```

2023-06-22 11:11 UTC, el-termikael commented on docs/adguard-for-android/installation.md
> +4. **Create a local VPN**. To filter all the traffic right on your device and not to rout it through a remote server AdGuard needs to set up a VPN connection.
```suggestion
4. **Create a local VPN**. In order to filter all traffic directly on your device and not route it through a remote server, AdGuard needs to establish a VPN connection.
```

2023-06-22 11:11 UTC, el-termikael commented on docs/adguard-for-android/installation.md
> +If your device runs on Android 7-9, after setting up a local VPN, you'll be prompted with a screen to install a root certificate and configure HTTPS filtering.
```suggestion
If your device is running Android 7–9, you'll be prompted to install a root certificate and configure HTTPS filtering after the local VPN setup.
```

2023-06-22 11:11 UTC, el-termikael commented on docs/adguard-for-android/installation.md
> +After you hit *Install now*, a prompt will pop up requesting you to authenticate the certificate installation using a password or fingerprint.
```suggestion
After you tap *Install now*, a prompt will appear asking you to authenticate the certificate installation with a password or fingerprint.
```

2023-06-22 15:21 UTC, anastasiia-fedotova commented on docs/adguard-for-android/installation.md
> +    * head over to [our website](https://adguard.com/en/adguard-android/overview.html) and tap the *Download* button
доне

2023-06-26 14:39 UTC, el-termikael approved these changes

2023-06-26 14:39 UTC, merged