[AGM-1212] Specify that regex are supported for $network rules
AdguardTeam/KnowledgeBase pull request #22
Opened 2022-10-03 09:51 UTC by DashaBu

2022-10-03 12:29 UTC, el-termikael submitted a review, later dismissed

2022-10-03 12:29 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +5. `/regexp/$network` - blocks access to all addresses that matches the `regexp` regular expression.
```suggestion
5. `/regexp/$network` blocks access to all addresses that match the `regexp` regular expression.
```

2022-10-03 12:29 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> + > Special characters: if the regular expression is used to exclude the IP address, use `+` sign which indicates *one or more*, `[]` sign matches a single number that is contained within the brackets
```suggestion
 > Special characters: if a regular expression is used to exclude an IP address, use the `+` sign that indicates *one or more*. The `[]` sign matches a single number in the brackets and the `{}` sign specifies the amount of times the number before can repeat itself.
```

2022-10-03 12:29 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +* `/.+:[1-3][0-9]{2,5}/$network` - blocks access to all IP addresses that ends with :100, :100000, 122, 122222 etc.
```suggestion
* `/.+:[1-3][0-9]{2,5}/$network` blocks access to all IP addresses that end with :100, :100000, 122, 122222, etc.
```
и выше давай тире тоже уберём

2022-10-03 12:48 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +* `/.+:[1-3][0-9]{2,5}/$network` - blocks access to all IP addresses that ends with :100, :100000, 122, 122222 etc.
Точно нужен ещё один пример? Похоже, что он по сути показывает то же, что и [этот](https://github.com/AdguardTeam/KnowledgeBase/pull/22/files#diff-190ba525f7c4d0b0eda33dab9df98df01d3ac072d6aeef951f044c96d58a25c9R710). И описание у этого правила получилось некорректное.

2022-10-05 09:52 UTC, sxgunchenko approved these changes

2022-10-05 09:54 UTC, vbagirov requested changes

2022-10-05 09:54 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +4. If the IP part starts and ends with `/` character, it's treated as a [regular expression](/general/ad-filtering/create-own-filters.md#regular-expressions-support).
Кажется, анкор называется `#regexp-support`, проверь

Плюс можно гиперссылку не просто закинуть на "regular expressions", а дописать отдельное предложение в духе "Подробнее о регулярных выражениях тут"

2022-10-05 10:05 UTC, vbagirov approved these changes

2022-10-05 10:57 UTC, merged