[AGM-1649] Update har.md for 4.0
AdguardTeam/KnowledgeBase pull request #224
Opened 2023-07-03 06:09 UTC by vyanovsky

Update har.md in accordance with AdGuard for Android v4.0

2023-07-03 07:56 UTC, Versty approved these changes

2023-07-03 10:02 UTC, el-termikael requested changes

2023-07-03 10:02 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/har.md
> +2. Tap **General**.
suggest merging a few steps into one:
Tap **General** → **Advanced** → **Low-level settings**.

2023-07-03 10:02 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/har.md
> +5. Scroll down and in the "Filtering" section activate **Capture HAR**.
5. Scroll down and activate **Capture HAR** in the **Filtering** section.

2023-07-03 10:02 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/har.md
> +6. Now reproduce the problem - open the app, perform the necessary actions (to make the ad appear etc.).
6. Open the app and perform the necessary actions to reproduce the problem.

2023-07-03 10:02 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/har.md
> +9. Tap **Export logs and system info**, then tap **Allow** (if necessary) and **Save**.
```suggestion
9. Tap **Export logs and system info** → **Allow** (if necessary) → **Save**.
```

2023-07-03 11:05 UTC, vyanovsky commented on docs/adguard-for-android/solving-problems/har.md
> +5. Scroll down and in the "Filtering" section activate **Capture HAR**.
Filtering это просто секция, поэтому не хочется путать его болдом, ведь болдом во всей остальной инструкции выделено все что нужно нажимать

2023-07-03 14:35 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/har.md
> +5. Scroll down and in the "Filtering" section activate **Capture HAR**.
кавычки лишние

2023-07-04 13:55 UTC, el-termikael approved these changes

2023-07-04 14:57 UTC, merged