[AGM-1662] Update system-wide-filtering.md
AdguardTeam/KnowledgeBase pull request #244
Opened 2023-07-20 13:24 UTC by vyanovsky

Update the article in accordance with AdGuard for iOS 4.5

2023-07-24 07:44 UTC, Versty approved these changes

2023-07-27 08:11 UTC, el-termikael requested changes

2023-07-27 08:11 UTC, el-termikael commented on docs/adguard-for-ios/solving-problems/system-wide-filtering.md
> +System-wide filtering means blocking ads and trackers beyond the Safari browser, i.e. in all other apps and browsers. This article will tell you how to enable it on your iOS device.
ну не во всех мы блочить можем, не надо

2023-07-27 08:11 UTC, el-termikael commented on docs/adguard-for-ios/solving-problems/system-wide-filtering.md
> + 1. Use AdGuard DNS filter (*Protection* 🛡 → *DNS protection* → *DNS filtering* → *DNS filters* → *AdGuard DNS Filter*).
опять же момент про эмодзи

2023-07-27 08:11 UTC, el-termikael commented on docs/adguard-for-ios/solving-problems/system-wide-filtering.md
> + 1. Use AdGuard DNS filter (*Protection* 🛡 → *DNS protection* → *DNS filtering* → *DNS filters* → *AdGuard DNS Filter*).
опять же момент про эмодзи
AdGuard DNS fllter

2023-07-27 08:11 UTC, el-termikael commented on docs/adguard-for-ios/solving-problems/system-wide-filtering.md
> + 1. Use AdGuard DNS filter (*Protection* 🛡 → *DNS protection* → *DNS filtering* → *DNS filters* → *AdGuard DNS Filter*).
AdGuard DNS filter

2023-07-27 09:25 UTC, vyanovsky commented on docs/adguard-for-ios/solving-problems/system-wide-filtering.md
> +For the sake of the example, let's add [OISD Big filter](https://oisd.nl/).
кем? глянь сайт, создатель его называет именно oisd big (еще маленькими буквами), лист/блоклист уже просто как дополнительное слово

для макс соответствия автору можно поправить на oisd big list

2023-07-27 10:27 UTC, vyanovsky commented on docs/adguard-for-ios/solving-problems/system-wide-filtering.md
> + 1. Use AdGuard DNS filter (*Protection* 🛡 → *DNS protection* → *DNS filtering* → *DNS filters* → *AdGuard DNS Filter*).
про эмодзи в соседнем пре ответил

2023-07-27 11:57 UTC, el-termikael commented on docs/adguard-for-ios/solving-problems/system-wide-filtering.md
> +For the sake of the example, let's add [OISD Big filter](https://oisd.nl/).
у нас, чекни краудин

2023-07-27 12:11 UTC, vyanovsky commented on docs/adguard-for-ios/solving-problems/system-wide-filtering.md
> +For the sake of the example, let's add [OISD Big filter](https://oisd.nl/).
ну я знаю, значит скорее под вопрос стоит поставить почему мы так не совсем верно называем его в наших продуктах

2023-07-28 08:17 UTC, el-termikael approved these changes

2023-07-28 08:21 UTC, merged