[AGM-1662] Update overview.md (iOS)
AdguardTeam/KnowledgeBase pull request #245
Opened 2023-07-24 04:37 UTC by vyanovsky

Some changes in accordance with AdGuard for iOS 4.5

2023-07-24 08:09 UTC, Versty commented on docs/adguard-for-ios/overview.md
> +![Light theme *mobile_border](https://uploads.adguard.org/homelight.jpeg)
Upload both screenshots to cdn

2023-07-24 08:38 UTC, Versty approved these changes

2023-07-27 08:04 UTC, el-termikael requested changes

2023-07-27 08:04 UTC, el-termikael commented on docs/adguard-for-ios/overview.md
> +In DNS filtering you can customize your DNS traffic by enabling AdGuard DNS filter, adding custom DNS filters and using DNS
DNS filtering allows you to customize your DNS traffic by enabling the AdGuard DNS filter, adding custom DNS filters, and using the DNS block-/allowlist.

2023-07-27 08:04 UTC, el-termikael commented on docs/adguard-for-ios/overview.md
> +*Protection* 🛡 icon (the second icon in the bottom menu bar) → *DNS protection* → *DNS filtering*
не уверена, что использовать в кб эмодзи хорошая идея

2023-07-27 08:04 UTC, el-termikael commented on docs/adguard-for-ios/overview.md
> +![Activity screen *mobile_border](https://cdn.adguard.com/content/github/ad_blocker/ios/activity.png)
мы же не используем cdn.adguard.com

2023-07-27 08:04 UTC, el-termikael commented on docs/adguard-for-ios/overview.md
> +Here AdGuard displays stats about device's DNS requests, such as total number, number of blocked requests and data saved by blocking them. AdGuard can display the stats for a day, a week, a month, or
This is where AdGuard displays statistics about the device's DNS requests, such as total number, number of blocked requests and data saved by blocking them. AdGuard can display the statistics for a day, a week, a month or in total.
или
Here, AdGuard displays statistics about the device's DNS requests, such as the total number of requests, the number of requests blocked, and the amount of data saved as a result of the blocking. AdGuard can display the statistics for a day, a week, a month or in total.

2023-07-27 09:34 UTC, vyanovsky commented on docs/adguard-for-ios/overview.md
> +*Protection* 🛡 icon (the second icon in the bottom menu bar) → *DNS protection* → *DNS filtering*
а почему нет? так нагляднее когда юзеру надо объяснить какую иконку, ведь на этом шаге в юае текста Protection юзер не видит

2023-07-27 09:44 UTC, vyanovsky commented on docs/adguard-for-ios/overview.md
> +*Protection* 🛡 icon (the second icon in the bottom menu bar) → *DNS protection* → *DNS filtering*
вот тут например юзаем эмодзи давно

https://adguard-vpn.com/kb/adguard-vpn-for-ios/overview/#app-settings

2023-07-27 09:45 UTC, vyanovsky commented on docs/adguard-for-ios/overview.md
> +![Activity screen *mobile_border](https://cdn.adguard.com/content/github/ad_blocker/ios/activity.png)
такая ссыль в таске была

2023-07-27 09:51 UTC, vyanovsky commented on docs/adguard-for-ios/overview.md
> +In DNS filtering you can customize your DNS traffic by enabling AdGuard DNS filter, adding custom DNS filters and using DNS
blocklist/allowlist лучше полностью оставить думаю, т.к. специфичные термины, не для всех очевидна дихотомия

2023-07-27 10:22 UTC, vyanovsky commented on docs/adguard-for-ios/overview.md
> +In DNS filtering you can customize your DNS traffic by enabling AdGuard DNS filter, adding custom DNS filters and using DNS
и артикли the кажется немного перебор - тут перечисление что в целом можно делать (фичи), а так получается что "прям вот тот самый аг днс фильтр, и тот самый днс блоклист/аллоулист!!"

2023-07-27 10:23 UTC, vyanovsky commented on docs/adguard-for-ios/overview.md
> +In DNS filtering you can customize your DNS traffic by enabling AdGuard DNS filter, adding custom DNS filters and using DNS
Итого на основе твоего я б вот так предложил:

DNS filtering allows you to customize your DNS traffic by enabling AdGuard DNS filter, adding custom DNS filters, and using DNS blocklist/allowlist.

2023-07-27 11:52 UTC, el-termikael commented on docs/adguard-for-ios/overview.md
> +*Protection* 🛡 icon (the second icon in the bottom menu bar) → *DNS protection* → *DNS filtering*
где? не вижу

2023-07-27 11:53 UTC, el-termikael commented on docs/adguard-for-ios/overview.md
> +*Protection* 🛡 icon (the second icon in the bottom menu bar) → *DNS protection* → *DNS filtering*
можно описать — the shield icon, что-то такое
база знаний больше похожа на документацию, это должен быть чистый текст без заигрываний с пользователем

2023-07-27 11:57 UTC, el-termikael requested changes

2023-07-27 11:57 UTC, el-termikael commented on docs/adguard-for-ios/overview.md
> +In DNS filtering you can customize your DNS traffic by enabling AdGuard DNS filter, adding custom DNS filters and using DNS
AdGuard DNS filter пусть останется без артикля, потому что перед названиями фильтров их обычно не ставим, а перед чёрным и белым списком всё-таки нужен

2023-07-27 11:57 UTC, el-termikael commented on docs/adguard-for-ios/overview.md
> +*Protection* 🛡 icon (the second icon in the bottom menu bar) → *DNS protection* → *DNS filtering*
там эмодзи единичный, да и с его уместностью я бы поспорила

можно описать — the shield icon, что-то такое
база знаний больше похожа на документацию, это должен быть чистый текст без заигрываний с пользователем

2023-07-27 12:06 UTC, vyanovsky commented on docs/adguard-for-ios/overview.md
> +*Protection* 🛡 icon (the second icon in the bottom menu bar) → *DNS protection* → *DNS filtering*
я бы не назвал это заигрыванием, тут эмодзи имеет чисто информативный характер, чтобы облегчить понимание юзеру куда тыкать

все-таки это документация, призванная помочь юзеру понять как пользоваться / что делать

2023-07-28 08:17 UTC, el-termikael approved these changes

2023-07-28 08:22 UTC, merged