Reworked Overview
AdguardTeam/KnowledgeBase pull request #248
Opened 2023-07-27 16:18 UTC by ss-orlova

New text + screenshots

2023-07-28 08:54 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +##### HTTPS-filtered websites
@ameshkov @artemiv4nov тут будут какие-то изменения в ближайшее время? надо бы на Website exclusions заменить

2023-07-28 08:56 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +In this mode, AdGuard VPN acts as an outbound proxy server through which AdGuard routes its traffic. This allows AdGuard to create a VPN interface and block ads and trackers, while all traffic is rou
@ameshkov @artemiv4nov так можно написать или лучше вообще ничего про прокси не писать?

2023-07-28 08:57 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +* The **Manual proxy** routing mode requires root access on Android 10 and above as it's no longer possible to determine the name of the app associated with a connection filtered by AdGuard
@ameshkov @artemiv4nov тоже надо проверить

2023-07-28 09:02 UTC, el-termikael requested changes

2023-07-28 09:02 UTC, el-termikael commented on docs/adguard-for-android/overview.md
>  :::
закрывающий тег адмонишна удалила

2023-07-28 09:02 UTC, el-termikael commented on docs/adguard-for-android/overview.md
> +Use this section if you have any questions or suggestions regarding AdGuard for Android. We recomnend consulting *FAQ* or this knowledge base before contacting support.
recomnend

2023-07-28 09:02 UTC, el-termikael commented on docs/adguard-for-android/overview.md
> +Use this section if you have any questions or suggestions regarding AdGuard for Android. We recomnend consulting *FAQ* or this knowledge base before contacting support.
на фак можно ссылку дать

2023-07-28 09:05 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +There are three pre-configured protection levels. Here’s what features they have enabled:
да ес

2023-07-28 09:06 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +Use this section if you have any questions or suggestions regarding AdGuard for Android. We recomnend consulting *FAQ* or this knowledge base before contacting support.
ну фак доступен из приложения, нужна ли ссылка?

2023-07-28 09:13 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
>  :::
а на 372 строке?

2023-07-30 19:26 UTC, ameshkov commented on docs/adguard-for-android/overview.md
> +In this mode, AdGuard VPN acts as an outbound proxy server through which AdGuard routes its traffic. This allows AdGuard to create a VPN interface and block ads and trackers, while all traffic is rou
Я бы еще добавил, что таким образом приложение AdGuard отвечает за фильтрацию трафика **локально**, а AdGuard VPN отвечает за его отправку через **remote server**.

2023-07-30 19:26 UTC, ameshkov commented on docs/adguard-for-android/overview.md
> +* The **Manual proxy** routing mode requires root access on Android 10 and above as it's no longer possible to determine the name of the app associated with a connection filtered by AdGuard
Верно

2023-07-30 19:27 UTC, ameshkov commented on docs/adguard-for-android/overview.md
> +Use this section if you have any questions or suggestions regarding AdGuard for Android. We recomnend consulting *FAQ* or this knowledge base before contacting support.
ссылками кашу не испортишь

2023-07-30 19:29 UTC, ameshkov commented on docs/adguard-for-android/overview.md
> +##### HTTPS-filtered websites
В релизе пока не так. Когда будем менять названия - надо будет менять это и в КБ

2023-07-31 08:35 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +Use this section if you have any questions or suggestions regarding AdGuard for Android. We recomnend consulting *FAQ* or this knowledge base before contacting support.
добавила

2023-07-31 08:35 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +In this mode, AdGuard VPN acts as an outbound proxy server through which AdGuard routes its traffic. This allows AdGuard to create a VPN interface and block ads and trackers, while all traffic is rou
добавила

2023-07-31 08:35 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +##### HTTPS-filtered websites
хорошо

2023-07-31 13:50 UTC, el-termikael approved these changes

2023-08-02 12:08 UTC, ameshkov approved these changes

2023-08-04 04:05 UTC, artemiv4nov commented on docs/adguard-for-android/overview.md
Хорошо б сразу дописать про Apps management, новую вкладку, которая уже в релизе

2023-08-04 08:44 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +#   App management
@artemiv4nov вот отсюда и ниже

2023-08-04 08:49 UTC, merged