Fixes for section about rules priorities
AdguardTeam/KnowledgeBase pull request #258
Opened 2023-08-01 20:54 UTC by 105th

A few corrections to fix arithmetic errors and clarify some non-standard situations

2023-08-02 08:32 UTC, el-termikael requested changes

2023-08-02 08:32 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +If this modifier is used with an exclusion rule (`@@`), it completely disables blocking on corresponding pages. It is equivalent to using `$elemhide`, `$content`, `$urlblock`, `$jsinject`, `$extensio
```suggestion
When used with an exclusion rule (`@@`), this modifier completely disables blocking on the corresponding pages. It is equivalent to using the `$elemhide`, `$content`, `$urlblock`, `$jsinject`, `$extension` modifiers simultaneously, but only if this modifier is written in the rule and not added hidden, for example in the rule `@@example.com$removeheader`, which implicitly adds `$document`.
```

2023-08-02 08:32 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +In addition, each of these exceptions implicitly adds the two allowed content-type modifiers `$document,subdocument`, but not when these exceptions are obtained by using the `$document` alias. For th
```suggestion
In addition, each of these exceptions implicitly adds the two allowed content-type modifiers `$document,subdocument`, but not when these exceptions are obtained using the `$document` alias. In this case, `$subdocument` should be specified explicitly: `@@||example.com$document,subdocument`.
```

2023-08-02 08:32 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +`1 + (50 + 50/12) = 55.17 = 56` because rounding up is applied.
```suggestion
`1 + (50 + 50/12) = 55.17 = 56` due to rounding.
```

2023-08-02 11:53 UTC, el-termikael approved these changes

2023-08-04 10:49 UTC, ngorskikh commented on docs/general/ad-filtering/create-own-filters.md
> +When used with an exclusion rule (`@@`), this modifier completely disables blocking on the corresponding pages. It is equivalent to using the `$elemhide`, `$content`, `$urlblock`, `$jsinject`, `$exte
```suggestion
When used with an exclusion rule (`@@`), this modifier completely disables blocking on the corresponding pages. It is equivalent to using the `$elemhide`, `$content`, `$urlblock`, `$jsinject`, `$extension` modifiers simultaneously, but only if this modifier is written in the rule and not added implicitly, for example in the rule `@@example.com$removeheader`, which implicitly adds `$document`.
```

2023-08-04 10:52 UTC, ngorskikh commented on docs/general/ad-filtering/create-own-filters.md
> +`1 + 100000 + 10000 * 5 + (50 + 50 / 2) = 50076`.
```suggestion
`1 + 100000 + 10000 * 5 + (50 + 50 / 2) = 150076`.
```

2023-08-04 10:52 UTC, ngorskikh commented on docs/general/ad-filtering/create-own-filters.md
>  `@@||example.com^$elemhide,content,jsinject,urlblock,extension`
Теперь как раз надо разделить этот пример на два, эти правила не эквивалентны)

2023-08-04 10:52 UTC, ngorskikh commented on docs/general/ad-filtering/create-own-filters.md
> +`1 + (50 + 50/12) = 55.17 = 56` due to rounding.
Можно добавить ссылку на раздел, где написано, что округление в большую сторону.

2023-08-04 12:06 UTC, 105th commented on docs/general/ad-filtering/create-own-filters.md
>  `@@||example.com^$elemhide,content,jsinject,urlblock,extension`
@ngorskikh почему не эквивалентны?
вот выдержка [из документации](https://adguard.com/kb/general/ad-filtering/create-own-filters/#document-modifier): 
> If this modifier is used with an exclusion rule (@@), it completely disables blocking on corresponding pages. It is equivalent to using $elemhide, $content, $urlblock, $jsinject, $extension modifiers simultaneously

2023-08-04 12:08 UTC, 105th commented on docs/general/ad-filtering/create-own-filters.md
> +`1 + (50 + 50/12) = 55.17 = 56` due to rounding.
добавил

2023-08-09 09:03 UTC, el-termikael approved these changes

2024-07-26 20:28 UTC, ngorskikh commented on docs/general/ad-filtering/create-own-filters.md
>  `@@||example.com^$elemhide,content,jsinject,urlblock,extension`
@sfionov Вызываю поддержку с воздуха. В корлибсах нынче эти два правила не эквивалентны: из-за того, что в них нет модификаторов типа запроса, применяются некие типа запроса по-умолчанию (это было сделано не просто так, а по чьему-то строгому указанию, не помню, чьему):
`@@||example.com^$elemhide,content,jsinject,urlblock,extension` неявно содержит два типа запроса: `DOCUMENT` и `SUBDOCUMENT`. `@@||example.org^$document` неявно содержит только тип запроса `DOCUMENT`. Следовательно, приоритеты у них вычисляются разные. Кто прав, кто виноват, нипонятно :(

2026-09-15 22:01 UTC, closed without merging