[AGM-1686] Safari extensions
AdguardTeam/KnowledgeBase pull request #273
Opened 2023-08-10 12:40 UTC by ss-orlova

1. Added an article about Safari extensions
2. Fixed wrong info about the Safari Icon extension in installation.md
3. Fixed a block about Safari extensions in create-own-filters.md

2023-08-11 10:54 UTC, el-termikael requested changes

2023-08-11 10:54 UTC, el-termikael commented on docs/adguard-for-safari/extensions.md
> +*AdGuard Privacy* applies rules from filters that you may find in *Filters* → *Privacy*. It blocks tracking mechanisms and ensures that your browsing activity remains private.
```suggestion
*AdGuard Privacy* applies rules from filters that you can find in *Filters* → *Privacy*. It blocks tracking mechanisms and ensures that your browsing activity remains private.
```

2023-08-11 10:54 UTC, el-termikael commented on docs/adguard-for-safari/extensions.md
> +*AdGuard Social* applies rules from filters that you may find in *Filters* → *Social Widgets* and *Filters* → *Annoyances*. It blocks popups, social media buttons, online assistant windows, and other
в обоих предложениях that you may find, второе заменить бы чем-то

2023-08-11 10:54 UTC, el-termikael commented on docs/adguard-for-safari/extensions.md
> +*AdGuard Privacy* applies rules from filters that you may find in *Filters* → *Privacy*. It blocks tracking mechanisms and ensures that your browsing activity remains private.
тут и ниже

2023-08-11 10:54 UTC, el-termikael commented on docs/adguard-for-safari/extensions.md
> +*AdGuard Social* applies rules from filters that you may find in *Filters* → *Social Widgets* and *Filters* → *Annoyances*. It blocks popups, social media buttons, online assistant windows, and other
ну или первое на that are located

2023-08-11 10:54 UTC, el-termikael commented on docs/adguard-for-safari/extensions.md
> +*AdGuard Advanced blocking* contains advanced rules that aren't converted into the format supported by Safari. This includes CSS rules, CSS selectors, and scriptlets that allow AdGuard to block compl
```suggestion
*AdGuard Advanced blocking* contains advanced rules that aren't converted into the format supported by Safari. This includes CSS rules, CSS selectors, and scriptlets that allow AdGuard to block complex ads — for example, on YouTube.
```

2023-08-13 20:02 UTC, ameshkov requested changes
The new article lacks screenshots

2023-08-15 08:56 UTC, el-termikael approved these changes

2023-08-21 14:21 UTC, merged