update path modifier description for non-basic rules
AdguardTeam/KnowledgeBase pull request #28
Opened 2022-10-26 16:16 UTC by slavaleleka

https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/1071

2022-10-26 16:53 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +
https://uploads.adguard.org/slbdzdrvg1b2y.png

2022-10-26 19:42 UTC, el-termikael requested changes

2022-10-26 19:42 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
>  > Please note that `path` modifier matches the query string as well.
```suggestion
> Please note that `$path` modifier matches the query string as well.
```

2022-10-27 06:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +> If `pattern` is not set for `$path`, rule will apply only on the main page of website.
можно добавить, что пусть `$path` эквивалентен `$path=/^\/$/`

2022-10-27 06:52 UTC, sxgunchenko approved these changes

2022-10-27 09:17 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> If `pattern` is not set for `$path`, rule will apply only on the main page of website.
я бы не стал добавлять, как будто немного лишняя подробность для того чтобы просто сделать правило

2022-10-28 14:07 UTC, el-termikael approved these changes

2022-10-28 14:07 UTC, merged

2022-10-28 14:18 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +
оо норм, короче несколько цитат надо разделять пустой строкой
https://uploads.adguard.org/slbdzdrvyc30b.png