Fix multiple quotes, lists, etc.
AdguardTeam/KnowledgeBase pull request #30
Opened 2022-10-28 21:01 UTC by slavaleleka

2022-10-28 21:32 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> * `POST` request types are supported only by AdGuard for Windows, Mac, and Android, **running CoreLibs version 1.10 or later**.
https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/1068

2022-11-01 19:31 UTC, vbagirov requested changes

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +    * **`string`** — a sequence of characters. It is matched against the header value lexicographically;
ты билдил локально, оно так поймет что тут сдвиг?

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +* `@@||example.com^$content` disables all HTML filtering and replace rules rules on pages at `example.com` and all subdomains.
Судя по всему, тут дважды `rules` повторилось. Плюс предлагаю так перефразировать:

* `@@||example.com^$content` disables all HTML filtering rules and replace rules on pages at `example.com` and all its subdomains.

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +* `searchqueries` disables [Hide your search queries](../stealth-mode#searchqueries)
Предлагаю все названия опций стелс мода выделить жирным или ещё как-то. Можно также добавить слово `option` после каждого пункта, например

```* `searchqueries` disables [**Hide your search queries**](../stealth-mode#searchqueries) option```

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
>  $stealth [= opt1 [| opt2 [| opt3 [...]]]]
меня квадратные скобки смущают. Их же нет в самом синтаксисе, они точно нужны тут?

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +> Blocking cookies and removing tracking parameters is achieved by using rules with [`$cookie`](#cookie-modifier) and [`$removeparam`](#removeparam-modifier) modifiers. Exception rules with only `$st
URL или домен?

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +For the requests matching a `$csp` rule, we will strengthen response security policy by adding additional content security policy equal to the `$csp` modifier contents. `$csp` rules are applied indep
>adding additional content security policy

не очень звучит, может так?

...by enhancing the content security policy, similar to the content security policy of the `$csp` modifier contents.

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +`$denyallow` modifier allows to avoid creating additional rules when it is needed to disable a certain rule for a specific domains. `$denyallow` matches only target domains and not referrer domains.
либо "for a specific domain", либо "for specific domains"

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +Rules with `$removeparam` modifier are intended to to strip query parameters from requests' URLs. Please note that such rules are only applied to `GET`, `HEAD`, `OPTIONS`, and [sometimes](#removepara
>intended to to strip

повтор

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +* `||example.org^$hls=/regexp/options` removes segments where the URL, or, if a certain option is present, one of the tags, matches the regular expression `regexp`. Available `options` are:
Сложно читается, я бы вот эту часть убрал в скобки:

>or, if a certain option is present, one of the tags,

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +* `||example.com/videos/$mp4` blocks a video downloads from `||example.com/videos/*` and changes the response to a video placeholder.
Либо "blocks a video download", либо "blocks all video downloads"

2022-11-01 19:31 UTC, vbagirov commented on docs/general/ad-filtering/create-own-filters.md
> +> Learn more [how to debug extended selectors](#selectors-debugging-mode).
Learn more about ...

2022-11-01 20:03 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +##### **`$domain`** {#domain-modifier}
по сути это всё таки подзаголовок. у меня есть идея потом эти подзаголовки собирать в небольшие содержания для отдельных разделов

2022-11-01 20:05 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +    * **`string`** — a sequence of characters. It is matched against the header value lexicographically;
билдил конечно. ровно на один таб больше чем предыдущий отступ. всё ок
https://uploads.adguard.org/slbdzdrv04555.png

2022-11-01 20:06 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
>  $stealth [= opt1 [| opt2 [| opt3 [...]]]]
квадратные скобки обычно обозначают опциональную часть - по крайней мере так обычно пишут в синтаксисе команд в терминале и технической документации

2022-11-01 20:10 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
>  $stealth [= opt1 [| opt2 [| opt3 [...]]]]
квадратные скобки подразумевают необязательность параметров. таков синтаксис синтаксиса, они нужны

2022-11-01 20:16 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> Blocking cookies and removing tracking parameters is achieved by using rules with [`$cookie`](#cookie-modifier) and [`$removeparam`](#removeparam-modifier) modifiers. Exception rules with only `$st
видимо домен. поправил

2022-11-01 20:26 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +* `||example.org^$hls=/regexp/options` removes segments where the URL, or, if a certain option is present, one of the tags, matches the regular expression `regexp`. Available `options` are:
попытался перефразировать так:
```
removes segments where the URL or one of the tags (for certain present option) is matched by the regular expression `regexp`
```

2022-11-02 05:51 UTC, sxgunchenko requested changes

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
>  ##### `$replace` rules features
раз другие заголовки убрали, этот тоже надо?
```suggestion
**`$replace` rules features**
```
или просто
```suggestion
**Features**
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +  * **`strategy`** — string for [Same-Site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies) strategy to make cookie use.
якорь в ссылке не работает (может раньше работал, не знаю)

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
>    * Makes the cookie use [Same-Site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies) "lax" strategy.
и тут неработающий якорь

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +#### **`$network`**
```suggestion
#### **`$network`** {#network-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +#### **`$redirect-rule`**
```suggestion
#### **`$redirect-rule`** {#redirect-rule-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
может тут убрать маркер примеров?
```suggestion
```
тут весь раздел - пример

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +**Basic syntax:**
тут и ниже недозаголовки заканчиваются двоеточием, а `Syntax` и `Examples` обычно не заканчиваются - это специально? может стоило оставить их обычными заголовками?

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
>  #### **`$removeheader`**
```suggestion
#### **`$removeheader`** {#removeheader-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +> ##### **Compatibility with different versions of AdGuard** {#removeparam-modifier-compatibility}
тут точно нужен заголовок?

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +**Restrictions**
у других модификаторов ограничения оформленны через blockquotes

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
>  #### **`$hls`**
```suggestion
#### **`$hls`** {#hls-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
>  #### **`$jsonprune`**
```suggestion
#### **`$jsonprune`** {#jsonprune-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
>  #### **`noop`**
```suggestion
#### **`noop`** {#noop-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +#### **`$empty` (deprecated)**
```suggestion
#### **`$empty` (deprecated)** {#empty-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +#### **`$mp4` (deprecated)**
```suggestion
#### **`$mp4` (deprecated)** {#mp4-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +### **`$path`**
```suggestion
### **`$path`** {#non-basic-path-modifier}
```

2022-11-02 05:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +### **`url`**
```suggestion
### **`url`** {#non-basic-url-modifier}
```

2022-11-02 08:56 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +#### Example: Blocking by domain name
содержание справа строится из первых двух уровней заголовков — `##` и `###`. кажется так лучше
https://uploads.adguard.org/slbdzdrvgkb3p.png

2022-11-02 09:04 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +**Basic syntax:**
из-за того что `Syntax` и `Examples` были заголовками, в разных местах они были разного размера. к тому же нет особого смысла держать их как заголовки потому что якорей на них нет

2022-11-02 09:06 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> ##### **Compatibility with different versions of AdGuard** {#removeparam-modifier-compatibility}
да, иначе якорь не работает

2022-11-02 09:12 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> Rules with `$webrtc` modifier are still supported by AdGuard Browser extension.
тогда уж и все остальные продукты надо перечислять. предлагаю пока оставить как есть

2022-11-02 09:22 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +**Basic syntax:**
тогда тут нужны двоеточия?

2022-11-02 09:23 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +**Basic syntax:**
на двоеточиях не настаиваю, уберу

2022-11-02 10:40 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +##### **`$third-party`**
тут и ниже модификаторы остались без якорей (не знаю, нужны ли они везде - если нет, то можно забить)

2022-11-02 10:40 UTC, sxgunchenko approved these changes

2022-11-02 10:49 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +##### **`$third-party`**
пока нет нужны, я бы не стал добавлять в этом пре

2022-11-07 11:02 UTC, el-termikael approved these changes

2022-11-07 11:12 UTC, merged