Add description for "Filter HTTP/3" in AdGuard for Mac
AdguardTeam/KnowledgeBase pull request #300
Opened 2023-09-04 12:41 UTC by ss-orlova

2023-09-04 14:08 UTC, el-termikael requested changes

2023-09-04 14:08 UTC, el-termikael commented on docs/adguard-for-mac/solving-problems/advanced-settings.md
>  Changing *Low-level settings* can cause problems with the performance of AdGuard, may break the Internet connection or compromise your security and privacy. You should only open this section if you a
может и вначале may?

2023-09-04 14:08 UTC, el-termikael commented on docs/adguard-for-mac/solving-problems/advanced-settings.md
>  Changing *Low-level settings* can cause problems with the performance of AdGuard, may break the Internet connection or compromise your security and privacy. You should only open this section if you a
надо понять, насколько это высокий риск с производительностью адгард

2023-09-04 14:08 UTC, el-termikael commented on docs/adguard-for-mac/solving-problems/advanced-settings.md
> +To go to *Advanced settings*, click the AdGuard icon in the tray menu → click the gear icon → select *Advanced* → *Advanced settings*.
мне кажется, что когда стрелочки ставим, лучше указывать путь, а если описываем, то лучше просто текстом

2023-09-04 14:08 UTC, el-termikael commented on docs/adguard-for-mac/solving-problems/advanced-settings.md
> +To go to *Advanced settings*, click the AdGuard icon in the tray menu → click the gear icon → select *Advanced* → *Advanced settings*.
```suggestion
To go to *Advanced settings*, click the AdGuard icon in the tray menu, click the gear icon, and select *Advanced* → *Advanced settings*.
```

2023-09-04 14:10 UTC, ss-orlova commented on docs/adguard-for-mac/solving-problems/advanced-settings.md
>  Changing *Low-level settings* can cause problems with the performance of AdGuard, may break the Internet connection or compromise your security and privacy. You should only open this section if you a
угу, давай
ну и кстати это не low-level, надо тоже поправить

2023-09-04 14:10 UTC, ss-orlova commented on docs/adguard-for-mac/solving-problems/advanced-settings.md
> +To go to *Advanced settings*, click the AdGuard icon in the tray menu → click the gear icon → select *Advanced* → *Advanced settings*.
давай тогда целиком без стрелочек

2023-09-04 15:32 UTC, el-termikael approved these changes

2023-09-05 08:13 UTC, Stillness-2 approved these changes

2023-09-05 10:48 UTC, merged