Update article about license activation
AdguardTeam/KnowledgeBase pull request #344
Opened 2023-10-04 14:25 UTC by ss-orlova

Screenshots + new path for Android

2023-10-04 14:34 UTC, el-termikael requested changes

2023-10-04 14:34 UTC, el-termikael commented on docs/general/license/activation.md
> +![Expired license screen *border](https://cdn.adtidy.org/blog/new/eapwtexp.png)
нужны отступы тут и ниже, чтобы список получился

2023-10-04 14:34 UTC, el-termikael commented on docs/general/license/activation.md
> +Alternatively, select *License* in the upper right corner of the main screen and click *Activate*.
чтобы скрины и текст относились к первому пункту

2023-10-04 14:34 UTC, el-termikael commented on docs/general/license/activation.md
> +![Activating a license *border](https://cdn.adtidy.org/blog/new/lnzz5activate-license.png)
аналогично

2023-10-04 15:02 UTC, ss-orlova commented on docs/general/license/activation.md
> +![Activating a license *border](https://cdn.adtidy.org/blog/new/lnzz5activate-license.png)
пофиксила

2023-10-05 14:03 UTC, el-termikael approved these changes

2023-10-05 14:38 UTC, merged