Add Safari settings guide for adguard to take effect
AdguardTeam/KnowledgeBase pull request #362
Opened 2023-10-27 09:27 UTC by ETOgaosion

Add Safari settings guide for adguard to take effect, hope to guide others to avoid common issue.

Here is preview image of modified contents:

<img width="1076" alt="截屏2023-10-27 17 25 21" src="https://github.com/AdguardTeam/KnowledgeBase/assets/57280232/7dec16dc-c5cf-43da-ad98-ed589f387690">

2023-10-27 09:29 UTC, ETOgaosion commented
You can download the pictures with the image bed url I use in the file, put them on your cdn host, and rename it as commented

2023-11-07 13:21 UTC, ETOgaosion commented
@ameshkov Hello Mr. would u consider my edition~

2023-11-14 10:54 UTC, el-termikael requested changes
@ETOgaosion thank you for adding Safari settings guide! please make suggested changes and we'll be able to merge it into master

2023-11-14 10:54 UTC, el-termikael commented on docs/adguard-for-safari/installation.md
> +1. To make Adguard take effects on websites, *content blocker* setting must be enabled. you can either enable for all website or select those ones you want.
```suggestion
1. To make AdGuard take effects on websites, the *Content Blockers* setting must be enabled. You can either enable for all websites or select the ones you want.

2023-11-14 10:54 UTC, el-termikael commented on docs/adguard-for-safari/installation.md
> +    Here is where to set *content blocker* on MacOS Safari: click *Preference* → *Websites* → *Content Blockers*, if you want to enable adguard on every website, turn *When visiting other websites* t
```suggestion
On macOS, click *Preference* → *Websites* → *Content Blockers*. If you want to enable AdGuard on every website, turn *When visiting other websites* to *On*.

2023-11-14 10:54 UTC, el-termikael commented on docs/adguard-for-safari/installation.md
> +    As for iOS (take ipad pro for example), go *Settings* → *Safari* → *Content Blockers*, turn option to *yes*.
```suggestion
On iOS, go *Settings* → *Safari* → *Content Blockers*, and set the option to *Yes*.

2023-11-16 13:32 UTC, ETOgaosion commented
Yeah, detail issues, my language mistakes(qaq).

Now accepted all your suggestions~

2023-12-13 12:04 UTC, el-termikael approved these changes

2023-12-13 12:05 UTC, merged