Fix modifiers description
AdguardTeam/KnowledgeBase pull request #365
Opened 2023-11-03 06:46 UTC by anastasiia-fedotova

fixed `$inline-font` and  `$inline-script` modifiers description

2023-11-07 12:08 UTC, Alex-302 requested changes

2023-11-07 12:08 UTC, Alex-302 commented on docs/general/ad-filtering/create-own-filters.md
> +The `$inline-font` modifier is designed to block websites' attempts to embed fonts directly into the main page through Content Security Policy (CSP). It aids in enhancing user security and privacy by
```suggestion
The `$inline-font` modifier is designed to block inline fonts, that embed into the web page, using Content Security Policy (CSP). It improves security and privacy by preventing the applying inline fonts that could be used for data collection and fingerprinting. The rule `||example.org^$inline-font` is converting into the CSP syntax rule:
```

`E.g.` тут врял ли уместно, т.к. это не пример, а расшифровка сокращённого вида правила.

2023-11-07 12:08 UTC, Alex-302 commented on docs/general/ad-filtering/create-own-filters.md
> +The `$inline-script` modifier is designed to block inline JavaScript within a page's HTML. It bolsters security and privacy by halting the execution of potentially malicious scripts without user cons
```suggestion
The `$inline-script` modifier is designed to block inline JavaScript, that embed into the web page, using Content Security Policy (CSP). It improves security and privacy by preventing the applying inline advertising or potentially malicious scripts. The rule `||example.org^$inline-script` is converting into the CSP syntax rule:
```

2023-11-09 09:14 UTC, anastasiia-fedotova commented on docs/general/ad-filtering/create-own-filters.md
> +The `$inline-font` modifier is designed to block websites' attempts to embed fonts directly into the main page through Content Security Policy (CSP). It aids in enhancing user security and privacy by
fixed

2023-11-09 09:57 UTC, el-termikael requested changes

2023-11-09 09:57 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +The `$inline-script` modifier is designed to block inline JavaScript embedded into the web page, using Content Security Policy (CSP). It improves security and privacy by preventing application of inl
```suggestion
The `$inline-script` modifier is designed to block inline JavaScript embedded into the web page, using Content Security Policy (CSP). It improves security and privacy by preventing application of inline ads or potentially malicious scripts. The rule `||example.org^$inline-script` is converting into the CSP-syntax rule:
```
или into the rule rule with CSP syntax

2023-11-09 09:57 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +The `$inline-font` modifier is designed to block inline fonts embedded into the web page, using Content Security Policy (CSP). It improves security and privacy by preventing application of inline fon
same

2023-11-09 10:06 UTC, anastasiia-fedotova commented on docs/general/ad-filtering/create-own-filters.md
> +The `$inline-script` modifier is designed to block inline JavaScript within a page's HTML. It bolsters security and privacy by halting the execution of potentially malicious scripts without user cons
done

2023-11-09 10:07 UTC, anastasiia-fedotova commented on docs/general/ad-filtering/create-own-filters.md
> +The `$inline-font` modifier is designed to block inline fonts embedded into the web page, using Content Security Policy (CSP). It improves security and privacy by preventing application of inline fon
done

2023-11-09 10:48 UTC, el-termikael approved these changes

2023-11-09 11:10 UTC, Alex-302 approved these changes

2023-11-09 11:12 UTC, merged