[AGM-1844] Safari extensions update
AdguardTeam/KnowledgeBase pull request #380
Opened 2023-11-29 10:43 UTC by puglieri

2023-11-29 16:02 UTC, ss-orlova commented on docs/adguard-for-safari/extensions.md
> +- *AdGuard for Safari* enables AdGuard's icon next to the search bar in Safari and allows using advanced rules to block complex ads
смущает, что маркированный список состоит из одного пункта теперь. может уберем и объединим с предыдущим предложением?

2023-11-29 16:04 UTC, ss-orlova commented on docs/adguard-for-safari/extensions.md
>  When enabling some Safari extensions, you might notice that they ask for **access to web page content** and **access to browsing history**. Here's why AdGuard for Safari needs them:
сейчас подумала, что у нас остался один экстеншн, который требует пермишнов. может поменять some extensions на AdGuard for Safari?

2023-11-30 07:16 UTC, el-termikael requested changes

2023-11-30 07:16 UTC, el-termikael commented on docs/adguard-for-safari/extensions.md
> +When enabling the extension *AdGuard for Safari*, you might notice that it requires **access to web page content** and **access to browsing history**. Here's why it needs these permissions:
```suggestion
When enabling the *AdGuard for Safari* extension, you might notice that it requires **access to web page content** and **access to browsing history**. Here's why it needs these permissions:
```

2023-11-30 07:16 UTC, el-termikael commented on docs/adguard-for-safari/extensions.md
> +When enabling the extension *AdGuard for Safari*, you might notice that it requires **access to web page content** and **access to browsing history**. Here's why it needs these permissions:
или просто When enabling *AdGuard for Safari*

2023-11-30 07:16 UTC, el-termikael commented on docs/adguard-for-safari/extensions.md
> +There is also one more extension responsible for other features: *AdGuard for Safari*, which enables AdGuard's icon next to the search bar in Safari and allows using advanced rules to block complex a
```suggestion
There is one more extension responsible for other features: *AdGuard for Safari*, which activates the AdGuard icon next to the search bar in Safari and allows using advanced rules to block complex ads.
```
как будто тут лучше aсtivate по смыслу, @ss-orlova?

2023-11-30 08:53 UTC, ss-orlova commented on docs/adguard-for-safari/extensions.md
> +When enabling the extension *AdGuard for Safari*, you might notice that it requires **access to web page content** and **access to browsing history**. Here's why it needs these permissions:
упоминание экстеншна норм тут, чтобы не путать с самой приложухой

2023-11-30 08:54 UTC, ss-orlova commented on docs/adguard-for-safari/extensions.md
> +There is also one more extension responsible for other features: *AdGuard for Safari*, which enables AdGuard's icon next to the search bar in Safari and allows using advanced rules to block complex a
хм, может add вообще?

2023-12-04 10:12 UTC, el-termikael approved these changes

2023-12-05 10:33 UTC, merged