Android TV instructions added
AdguardTeam/KnowledgeBase pull request #409
Opened 2023-12-27 13:07 UTC by puglieri

2023-12-27 13:14 UTC, slavaleleka commented on youtube-ads.md
how is this file related to the android tv instructions added? 

it's placed in the root directory. is it ok?

2023-12-27 13:30 UTC, puglieri commented on youtube-ads.md
It's not related, I've used it as a template/base for the new article (the article about YouTube is still there, it was just copy + overwrite)

2023-12-27 13:31 UTC, el-termikael requested changes

2023-12-27 13:31 UTC, el-termikael commented on youtube-ads.md
I guess it's a mistake
@puglieri youtube-ads.md is the file that must not be in this PR

2023-12-27 13:33 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/android-tv.md
> +* Open the installed TV Bro browser on your Android TV.
Unordered list style, replace asterisks with dashes

2023-12-27 13:33 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/android-tv.md
> +* Wait for a message in the terminal indicating the successful installation of the app.
a trailing whitespace needs to be added

2023-12-28 11:50 UTC, el-termikael commented on youtube-ads.md
> +Alternatively, you can also watch YouTube in a browser and there will be no ads if you have AdGuard installed and enabled.
you still need to remove this file from this PR

2023-12-28 11:50 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/adguard-for-android-tv.md
> +- Wait for a message in the terminal indicating the successful installation of the app.
and you still need to add an empty string below

2023-12-28 12:22 UTC, slavaleleka commented on docs/adguard-for-android/solving-problems/adguard-for-android-tv.md
> +The connection will be established.
так и задумано?
https://uploads.adguard.org/sllgfbvfjkp5g.png

2023-12-29 05:58 UTC, el-termikael approved these changes

2023-12-29 09:44 UTC, merged