[GH-372] Fix wording in the "Writing about AdGuard" article
AdguardTeam/KnowledgeBase pull request #414
Opened 2024-01-23 15:48 UTC by vbagirov

2024-01-23 15:48 UTC, vbagirov commented
Closes #372

2024-01-23 20:47 UTC, el-termikael requested changes

2024-01-25 09:21 UTC, el-termikael commented on docs/miscellaneous/contribute/writing-about-adguard.md
> +If you like AdGuard and want to spread the word and share your thoughts about it on social media, on a personal blog or a website, this article may interest you.
on social media, on a personal blog or a website — либо on social media, a personal blog or a website, либо on social media, on a personal blog or on a website,

2024-01-25 09:21 UTC, el-termikael commented on docs/miscellaneous/contribute/writing-about-adguard.md
> +If you like AdGuard and want to spread the word and share your thoughts about it on social media, on a personal blog or a website, this article may interest you.
ну и наверное оксфордской запятой не хватает

2024-01-25 09:37 UTC, el-termikael approved these changes

2024-01-25 10:22 UTC, merged