Fix mistakes in instructions
AdguardTeam/KnowledgeBase pull request #425
Opened 2024-02-19 10:05 UTC by SeverAnna

Updated instructions for taking screenshots

2024-02-19 10:36 UTC, Alex-302 commented on docs/guides/take-screenshot.md
> +- **Press the *Win + Shift + S* shortcut**
там ещё есть hold'ы в описании хоткеев. Для однообразности другие `hold [перечисление клавиш]` лучше заменить аналогично.

Для дроида - `hold`=>`press`, т.к. удерживать нажатыми кнопки не нужно (Press the Power and Volume down buttons at the same time)

2024-02-29 08:05 UTC, el-termikael requested changes

2024-02-29 08:05 UTC, el-termikael commented on docs/guides/take-screenshot.md
> +Sometimes  screenshots are requested by the support team for a better understanding. Here you will find all the necessary hotkeys you should know in order to take screenshots on your computer or mobi
лишний пробел затесался

2024-03-01 08:31 UTC, Alex-302 commented on docs/guides/take-screenshot.md
> +- **Press *Back* and *Home* at the same time**
Это для старых девайсов. На современных нет кнопки Домой или Назад.
Вот актуальная инструкция, включая бескнопконажимательный вариант
https://support.google.com/pixelphone/answer/2811098?hl=en&sjid=11252037228191748475-EU

2024-03-01 15:43 UTC, el-termikael requested changes

2024-03-04 13:28 UTC, el-termikael approved these changes

2024-03-04 16:47 UTC, merged