Updated descriptions of the features of the different AdGuard privacy protection levels
AdguardTeam/KnowledgeBase pull request #430
Opened 2024-02-22 22:49 UTC by nataMai

Updated descriptions of the features of the different AdGuard privacy protection levels as per AG-10938

2024-02-26 13:22 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +    This feature deletes all third-party cookies after their forced expiration. This includes your logins through social networks or other third-party services. You may need to re-log in to some webs
```suggestion
    This feature deletes all third-party cookies after their forced expiration. This includes your logins through social networks or other third-party services. You may need to re-log in to some websites periodically or experience other cookie-related issues. To block only tracking cookies, use the *Standard* protection level.
```

2024-02-26 13:23 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +    c. *Remove X-Client-Data header*. This feature prevents Google Chrome from sending its version and modifications information to Google domains (including DoubleClick and Google Analytics)
modifications information — нормально звучит?

2024-02-26 13:24 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +    This feature deletes all third-party cookies after their forced expiration. This includes your logins through social networks or other third-party services. You may need to re-log in to some webs
```suggestion
    This feature deletes all third-party cookies after their forced expiration. This includes your logins through social networks or other third-party services. You may need to re-log in to some websites periodically or experience other cookie-related issues. To block only tracking cookies, use the *Standard* protection level.
```

2024-02-26 13:25 UTC, ss-orlova commented on docs/adguard-for-android/overview.md
> +    g. *Block Push API*. This feature prevents your browsers from receiving notifications from servers, regardless of the status of your browser activity
а тут разве не важнее что они юзеру уведомления отправляют?

2024-02-26 14:19 UTC, ss-orlova approved these changes

2024-02-26 14:23 UTC, ss-orlova commented
еще линт на что-то ругается, но я кроме цифр не поняла пока. может @el-termikael в курсе?

2024-02-26 15:56 UTC, el-termikael commented
@ss-orlova в курсе, конечно. если во вскоде установлен маркдаунлинт, он эти ошибки сразу подчёркивает. можно прям оттуда по ссылке перейти, почитать о каждой (но там часто и из краткого описания понятно, что убрать/добавить)
+ повторно призываю посмотреть [мини-инструкцию по вскоду](https://www.notion.so/adguard/Visual-Studio-Code-48124ec8951046a996bfc1bee8bc0c5b)
и включить эти опции у себя в настройках, чтобы лишний раз не приходилось править часть ошибок форматирования

2024-02-27 11:14 UTC, vbagirov requested changes

2024-02-27 11:14 UTC, vbagirov commented on docs/adguard-for-android/overview.md
> + 3. **High**
Тут 3 идёт после 1, но я так понимаю это всё входит в чек линтера в любом случае

2024-02-27 11:14 UTC, vbagirov commented on docs/adguard-for-android/overview.md
> +    c. *Remove X-Client-Data header*. This feature prevents Google Chrome from sending its version and modifications information to Google domains (including DoubleClick and Google Analytics)
Я бы переписал на "…from sending information about its version and modifications…"

2024-02-27 11:14 UTC, vbagirov commented on docs/adguard-for-android/overview.md
> +    f. *Remove X-Client-Data header*  This feature prevents Google Chrome from sending its version and modifications information to Google domains (including DoubleClick and Google Analytics)
Точки не хватает после "header"

2024-02-27 11:14 UTC, vbagirov commented on docs/adguard-for-android/overview.md
> +    g. *Block Push API*. This feature prevents your browsers from receiving notifications from servers, regardless of the status of your browser activity
Я так понимаю имеется в виду, что если браузер не получит нотификейшн от сервера, то и юзеру не сможет его показать. Можно это прописать явно, наверное

2024-02-27 11:14 UTC, vbagirov commented on docs/adguard-for-android/overview.md
> +    k. *Remove X-Client-Data header*
Тут специально нет описания?

2024-02-27 13:40 UTC, vbagirov commented
> еще линт на что-то ругается, но я кроме цифр не поняла пока. может @el-termikael в курсе?

Trailing spaces это лишние пробелы в конце строки

2024-02-27 18:34 UTC, nataMai commented on docs/adguard-for-android/overview.md
> + 3. **High**
Поправила нумерацию, но не очень поняла, почему так получилось

2024-02-27 18:41 UTC, nataMai commented
Я прямо в гитхабовском редакторе правлю. Что мне в нем настроить, чтобы форматирование не ругалось?

2024-02-28 07:35 UTC, el-termikael commented
@nataMai так нельзя. все правки нужно вносить локально, во вскоде

2024-02-28 15:08 UTC, nataMai commented
Про VS code поняла. В прошлой КБ правила в вебовском редакторе. Помогите мне пожалуйста с этим ПРом, а следующий я тогда буду делать в VS code

2024-02-29 12:32 UTC, merged