Mac: Divide Overview into small articles
AdguardTeam/KnowledgeBase pull request #454
Opened 2024-03-26 17:36 UTC by ss-orlova

2024-03-27 13:39 UTC, el-termikael requested changes

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/browser-assistant.md
> +![The Assistant window](https://cdn.adtidy.org/content/kb/ad_blocker/mac/assistant_window.png)
а ты собирала локально, скрины не гигантские?

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/browser-assistant.md
> +- Manually block an ad
```suggestion
- Manually block ads
```

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/browser-assistant.md
> +- View website certificate and disable manage filtering (the lock icon next to the website name)
тут наверное вместо disable manage предполагалось

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/browser-assistant.md
> +1. Switch to the *Assistant tab*.
```suggestion
1. Switch to the *Assistant* tab.
```

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/extensions.md
> +Some userscripts are pre-installed, others you can be installed manually.
```suggestion
Some userscripts are pre-installed, others can be installed manually.
```

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/extensions.md
> +- Manually block an ad
```suggestion
- Manually block ads
```

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/extensions.md
> +- Manually block an ad
ну ок, видимо подразумевается отдельная случайно проскользнувшая рекламка, поэтому не настаиваю

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/network.md
> +By default, we also do not filter websites with Extended Validation (EV) certificates. If needed, you can enable the *Filter websites with EV certificates* option.
```suggestion
By default, AdGuard does not filter websites with Extended Validation (EV) certificates. If needed, you can enable the *Filter websites with EV certificates* option.
```

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/network.md
> +Make sure your Mac and your other device are connected to the same network and enter the proxy port on the second device (usually in the network settings). To filter HTTPS traffic as well, [download
как будто устройств у пользователя может быть только два

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/stealth.md
> +![Stealth Mode](https://cdn.adtidy.org/content/kb/ad_blocker/mac/stealth.png)
скрин в конце раздела как-то странно, не?

2024-03-27 13:39 UTC, el-termikael commented on docs/adguard-for-mac/features/stealth.md
> +![Stealth Mode](https://cdn.adtidy.org/content/kb/ad_blocker/mac/stealth.png)
давай между адмонишном и текстом его разместим мб

2024-03-28 17:40 UTC, ss-orlova commented on docs/adguard-for-mac/features/browser-assistant.md
> +- View website certificate and disable manage filtering (the lock icon next to the website name)
ой, пасиба

2024-03-28 17:42 UTC, ss-orlova commented on docs/adguard-for-mac/features/network.md
> +Make sure your Mac and your other device are connected to the same network and enter the proxy port on the second device (usually in the network settings). To filter HTTPS traffic as well, [download
хм, а как сформулировать?

2024-03-28 17:42 UTC, ss-orlova commented on docs/adguard-for-mac/features/network.md
> +Make sure your Mac and your other device are connected to the same network and enter the proxy port on the second device (usually in the network settings). To filter HTTPS traffic as well, [download
везде other?

2024-03-28 17:44 UTC, ss-orlova commented on docs/adguard-for-mac/features/network.md
> +Make sure your Mac and your other device are connected to the same network and enter the proxy port on the second device (usually in the network settings). To filter HTTPS traffic as well, [download
так, вроде переформулировала, скоро запушу

2024-03-28 17:45 UTC, ss-orlova commented on docs/adguard-for-mac/features/stealth.md
> +![Stealth Mode](https://cdn.adtidy.org/content/kb/ad_blocker/mac/stealth.png)
а так получится что он в начале, не супер симпатишно

2024-03-28 17:49 UTC, ss-orlova commented on docs/adguard-for-mac/features/browser-assistant.md
> +![The Assistant window](https://cdn.adtidy.org/content/kb/ad_blocker/mac/assistant_window.png)
ой, спасибо, поправлю

2024-03-28 17:51 UTC, ss-orlova commented on docs/adguard-for-mac/features/stealth.md
> +![Stealth Mode](https://cdn.adtidy.org/content/kb/ad_blocker/mac/stealth.png)
придумала что сделать

2024-03-29 10:02 UTC, el-termikael approved these changes

2024-03-29 15:47 UTC, merged