[WIP] update tld support section
AdguardTeam/KnowledgeBase pull request #48
Opened 2022-11-23 18:38 UTC by slavaleleka

2022-11-23 18:50 UTC, sxgunchenko requested changes

2022-11-23 18:50 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +For example, the cosmetic rule `example.*##.banner` will match any ICANN-registered TLD request, i.e. `example.com`, `example.net`, `example.org`, etc.
не, тут как раз не `ICANN-registered TLD`, а public suffixes - можно на него ссылку дать https://publicsuffix.org/list/

2022-11-24 07:54 UTC, ameshkov commented on docs/general/ad-filtering/create-own-filters.md
> +For example, the cosmetic rule `example.*##.banner` will match any ICANN-registered TLD request, i.e. `example.com`, `example.net`, `example.org`, etc.
In addition we should mention AdGuard for iOS and Safari here. There we use a shorter list of top-level-domains instead.

2022-11-24 08:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +For example, in the cosmetic rule `example.*##.banner` the part `.*` will match any [public suffix](https://publicsuffix.org/list/), i.e. `example.com`, `example.net`, `example.org`, etc.
я тут ещё подумал, что можно упомянуть термин eTLD (effective top-level domain, по сути синоним public suffix в данном контексте)

ну и мне кажется, что сейчас фраза не совсем корректно построена, может как-то так?
```suggestion
For example, in the cosmetic rule `example.*##.banner` the part `.*` matches any [public suffix (or eTLD)](https://publicsuffix.org/list/), i.e. the rule matches `example.com`, `sub.example.net`, `example.co.uk`, etc.
```

2022-11-24 11:06 UTC, sxgunchenko approved these changes

2022-11-24 12:30 UTC, ameshkov approved these changes

2022-11-24 12:31 UTC, ameshkov requested changes
We should really add a note about AdGuard for Safari and iOS limitations.

2022-11-24 13:17 UTC, slavaleleka commented
> We should really add a note about AdGuard for Safari and iOS limitations.

I will, the pr is still wip

2022-11-24 16:43 UTC, ameshkov approved these changes

2022-11-25 14:23 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +For basic rules the described logic will be applicable only for the domains specified in [`$domain` modifier](#domain-modifier), e.g. `||*/banners/*$image,domain=example.*`.
по идее лучше без will тут
```suggestion
For cosmetic rules, e.g. `example.*##.banner`, multiple domains are matched due to the part `.*`, i.e. `example.com`, `sub.example.net`, `example.co.uk`, etc.

For basic rules the described logic is applicable only for the domains specified in [`$domain` modifier](#domain-modifier), e.g. `||*/banners/*$image,domain=example.*`.
```

2022-11-25 14:23 UTC, sxgunchenko approved these changes

2022-11-25 16:17 UTC, merged