[AGM-2033] Update Uninstall utility screenshots
AdguardTeam/KnowledgeBase pull request #483
Opened 2024-05-02 16:31 UTC by vbagirov

2024-05-02 17:20 UTC, el-termikael approved these changes

2024-05-03 10:34 UTC, adbuker requested changes

2024-05-03 10:34 UTC, adbuker commented on docs/adguard-for-windows/installation.md
> +![Extended uninstall warning *border](https://cdn.adtidy.org/content/kb/ad_blocker/windows/installation/ab_extended_complete.jpg)
тут как будто нужная другая картинка, эта совпадает с `Extended uninstall finished *border`

2024-05-03 10:34 UTC, adbuker commented on docs/adguard-for-windows/installation.md
> +![Uninstall finished *border](https://cdn.adtidy.org/content/kb/ad_blocker/windows/installation/ab_standard_complete.jpg)
тут тогда тоже надо заблюрить как в расширенном

2024-05-03 10:39 UTC, adbuker approved these changes

2024-05-03 10:59 UTC, merged