ADG 5355 Ad Blocker Knowledge Base migration - General folder
AdguardTeam/KnowledgeBase pull request #5
Opened 2022-07-18 14:59 UTC by anastasiia-fedotova

2022-07-21 23:14 UTC, Alex-302 commented on docs/general/ad-filtering/how-to-create-ad-filters.md
>    2. Go to Console tab and run `console.dir($0)`.
Может маркдауна добавить, как здесь?
![image](https://user-images.githubusercontent.com/8361299/180330220-02779905-6cb5-46f1-826c-1f90788477ef.png)

2022-09-15 11:26 UTC, vbagirov requested changes

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/activation.md
> +In AdGuard for Windows and AdGuard for Mac, you can also use the [license key](what-is#license-key) to activate the license. Clicking the *Reset license* button logs you out from your device and unbi
```what-is.md#license-key```

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/activation.md
> +The license key can be activated on a [limited number of devices](what-is#devices). If the key has already been used on the maximum allowed number of devices, you need to unbind a device from your ac
тоже ՝.md` потерялось

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/activation.md
> +* by clicking the cross icon next to the device in your AdGuard account.
next to A device, кажется - можно же любой открепить

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/legacy.md
> +Initially (our veteran users will remember) licenses of the following types were available to activate AdGuard products:
не надо про ветеран юзерз тут

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/legacy.md
> +Premium keys (5+5 and more) and custom keys for 10+ devices that you purchased individually with the help of our managers.
какая-то незаконченная мысль

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/payment-options.md
> +AdGuard Ad Blocker can be bought on [adguard.com](https://adguard.com/en/license.html). AdGuard Pro for iOS can be bought on the App Store. Ad Blocker licenses are also sold by various distributors.
речь именно про лицензию, писать "AdGuard Ad Blocker can be bought" не совсем верно. Локаль тоже можно убрать из ссылки

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/payment-options.md
> +To get a refund, contact [our support team](mailto:support@adguard.com) and indicate the payment option you've used.
лучше убрать ссылку mailto и нигде её не использовать, а дать ссылку на статью про саппорт (посмотреть в структуре)

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/payment-options.md
> +## How to get a refund
тут где то можно написать что всё ин аккорданс ту термс оф сейл и сюда ссыль дать: 
https://adguard.com/terms-of-sale.html

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/what-is.md
> +An AdGuard license is a permission to use a specific AdGuard product.
почему specific?

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/what-is.md
> +AdGuard licenses exist in a form of license keys, activation codes, and product cards in the user's [AdGuard account](../account/register.md).
кажется in THE form of

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/what-is.md
> +1. **Trial licenses** are free time-limited licenses with full functionality:
тут все цифры перепроверены?

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/what-is.md
> +    AdGuard Ad Blocker Monthly subscription,
а у нас точно есть такая?

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/what-is.md
> +* Personal: three devices,
up to

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/what-is.md
> +> To extend the device limit, you can [upgrade](activation#how-to-upgrade-a-license) your license.
.md потерялось

2022-09-15 11:26 UTC, vbagirov commented on docs/general/license/what-is.md
> +> When unbinding a license, be sure you record the key in a safe place. You'll need the key for re-binding your license or transferring it to another account.
>When unbinding a license, be sure you record the key in a safe place

не нравится как сформулировано. 
When unbinding a license, be sure you write the license key down beforehand or note in some other (safe) way. You'll need ...

2022-09-15 11:26 UTC, vbagirov commented on docs/general/stealth-mode.md
> +
добавь тут блокквоутом что типа те или иные опции могут быть недоступны в зависимости от конкретного продукта в связи с ограничениями ОС или иными.

2022-09-15 11:26 UTC, vbagirov commented on docs/general/userscripts.md
> +First, let's get it clear. What is a userscript? Userscripts (we also call them "extensions") are, de-facto, mini-programs written in Javascript. They modify or extend the functionality of one or mor
>First, let's get it clear. What is a userscript?

вот эта часть не нужна

2022-09-15 11:26 UTC, vbagirov commented on docs/general/userscripts.md
> +AdGuard can significantly broaden website functionality by acting as a userscript manager. You can add your custom scripts or manage the existing ones in our three products: [AdGuard for Windows](ссы
ссылки

2022-09-15 11:26 UTC, vbagirov commented on docs/general/userscripts.md
> +> These userscripts come directly from the AdGuard developers, and we can guarantee that they are effective and safe. Remember: whenever you download a userscript from an unknown source, you expose y
ссылка ведёт на несуществующий анкор

2022-09-15 11:26 UTC, vbagirov commented on docs/general/userscripts.md
> +* **AdGuard Extra** - An extension that blocks advertising in difficult cases when the usual filter-based approach is not enough.
тут и далее тире короткие

2022-09-15 11:26 UTC, vbagirov commented on docs/general/userscripts.md
> +[Greasy Fork](https://greasyfork.org/) is a userscript catalog by [Stylish](#userstyles) creators. Unlike the above-mentioned userstyles.org, the scripts in this catalog undergo moderation, so their
```#userstyles``` - нет такого анкора кажется

2022-09-15 11:26 UTC, vbagirov commented on docs/general/userscripts.md
> +Here is a [mailto link](mailto:devteam@adguard.com?Subject=Userscript%20author%20license%20request&Body=Hello%2C%0A%0AMy%20userscript%28s%29%3A%20LINK).
напиши рядом явно мыло devteam@adguard.com, не все будут морочиться с мейлту

2022-09-15 11:54 UTC, anastasiia-fedotova commented on docs/general/account/register.md
> +1. User data, such as login credentials, preferred language and license info, that can be used for user identification;
Это Соня писала. Вот её комментарий: 

я бы сказала что есть два случая употребления слова account:
Log in using your AdGuard account — используйте данные о вас чтобы войти
Manage your licenses in your AdGuard account — зайдите в интерфейс учетной записи и делайте там свои дела

но, наверное, такое разбиение тут не нужно... да?

2022-09-15 12:00 UTC, anastasiia-fedotova commented on docs/general/account/register.md
> +> If you enter your email address while purchasing a license or receive a license accociated with your email address as a gift, an account will be created automatically. To set a password, you can fo
1. а как можно завести аккаунт случайно? не понимаю. 
2. как попасть в аккаунт, если не ты его заводил и не знаешь пароль?

2022-09-15 12:05 UTC, ss-orlova commented on docs/general/account/register.md
> +> If you enter your email address while purchasing a license or receive a license accociated with your email address as a gift, an account will be created automatically. To set a password, you can fo
1. если тебе подарили например (придет письмо что подарили и акк создался) / либо если завели на твою почту без твоего ведома (придет письмо что вы зареганы)
2. в первом случае в письме предложат установить пароль. думаю, если проигнорить, акк как-то пометится как неактивный (?). во втором случае предложат активировать акк, тоже не знаю что будет если проигнорить

2022-09-15 12:05 UTC, ss-orlova commented on docs/general/account/register.md
> +> If you enter your email address while purchasing a license or receive a license accociated with your email address as a gift, an account will be created automatically. To set a password, you can fo
но так или иначе в настройки зайти нельзя если пароля нет, это да

2022-09-15 12:08 UTC, ss-orlova commented on docs/general/userscripts.md
> +> These userscripts come directly from the AdGuard developers, and we can guarantee that they are effective and safe. Remember: whenever you download a userscript from an unknown source, you expose y
ох боже, аттеншн в заголовке...

2022-09-15 13:09 UTC, anastasiia-fedotova commented on docs/general/license/legacy.md
> +Premium keys (5+5 and more) and custom keys for 10+ devices that you purchased individually with the help of our managers.
а может вообще удалить про нестандартные лицензии отсюда? тут всё же про старые типы

2022-09-15 13:32 UTC, anastasiia-fedotova commented on docs/general/license/what-is.md
> +1. **Trial licenses** are free time-limited licenses with full functionality:
ага

2022-09-15 13:39 UTC, anastasiia-fedotova commented on docs/general/license/what-is.md
> +    AdGuard Ad Blocker Monthly subscription,
здесь имеется ввиду, что автоматическое списание средств происходит 1 раз в месяц или 1 раз в год

2022-09-15 13:48 UTC, anastasiia-fedotova commented on docs/general/userscripts.md
> +> These userscripts come directly from the AdGuard developers, and we can guarantee that they are effective and safe. Remember: whenever you download a userscript from an unknown source, you expose y
по идее Докузаурус сам сделает анкор из заголовка

2022-09-15 13:52 UTC, el-termikael commented on docs/general/userscripts.md
> +> These userscripts come directly from the AdGuard developers, and we can guarantee that they are effective and safe. Remember: whenever you download a userscript from an unknown source, you expose y
сделает, если будет такой заголовок:
### Userscripts {#where-can-you-get-more-userscripts}

2022-09-15 16:01 UTC, vbagirov requested changes

2022-09-15 16:01 UTC, vbagirov commented on docs/general/userscripts.md
> +AdGuard can significantly broaden website functionality by acting as a userscript manager. You can add your custom scripts or manage the existing ones in our three products: [AdGuard for Windows](/do
докс не надо

2022-09-15 16:01 UTC, vbagirov commented on docs/general/userscripts.md
> +> These userscripts come directly from the AdGuard developers, and we can guarantee that they are effective and safe. Remember: whenever you download a userscript from an unknown source, you expose y
Вроде всё ещё не сделано

2022-09-19 14:22 UTC, vbagirov approved these changes

2022-09-19 14:25 UTC, merged