Multiple wording and typo fixes
AdguardTeam/KnowledgeBase pull request #50
Opened 2022-11-25 12:55 UTC by anastasiia-fedotova

2022-11-25 14:15 UTC, slavaleleka requested changes

2022-11-25 14:15 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> Please note, that The features described in this section are intended for experienced users. They extend capabilities of "Basic rules", but in order to use them you need to have a basic understandi
по аналогии с другими "заметками" в этой статье
```suggestion
> Note
> 
> The features described in this section are intended for experienced users. They extend capabilities of "Basic rules", but in order to use them you need to have a basic understanding of the way your browser works.
```

2022-11-25 14:15 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +In the `$replace` value, two characters must be escaped: comma (`,`) and dollar (`$`). Use (`\`) for it. For example, an escaped comma looks like this: `\,`.
скобки можно убрать наверное. + бекслеш
```suggestion
In the `$replace` value, two characters must be escaped: comma `,` and dollar sign `$`. Use backslash `\` for it. For example, an escaped comma looks like this: `\,`.
```

2022-11-25 14:15 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +#### **`$redirect rule`** {#redirect-rule-modifier}
верните как было. потому что дефис — часть названия модификатора

2022-11-25 14:15 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> 2. There is another slash character (`/`) to the left of it;
```suggestion
> 2. There is another slash character `/` to the left of it;
```

2022-11-25 14:15 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> 3. There is another unescaped `$` character to the left of that slash character.
```suggestion
> 3. There is another unescaped dollar sign `$` to the left of that slash character.
```

2022-11-25 14:15 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +- `selector`— optional, a plain CSS selector, or a Sizzle compatible selector
```suggestion
- `selector` — optional, a plain CSS selector, or a Sizzle compatible selector
```

2022-11-28 15:23 UTC, slavaleleka approved these changes

2022-11-29 07:52 UTC, el-termikael approved these changes

2022-11-29 07:53 UTC, merged

2022-11-29 10:52 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> -#### Example: Blocking by domain name
почему решили убрать? в заголовках так могут писать
https://uploads.adguard.org/slbdzdrve1twc.png
https://uploads.adguard.org/slbdzdrvnqmoz.png

2022-11-29 11:21 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> -#### Example: Blocking by domain name
да, ты прав
если считаешь, что с example сильно лучше, вернём