[WIP] add description for trusted scriptlets
AdguardTeam/KnowledgeBase pull request #51
Opened 2022-11-28 18:06 UTC by slavaleleka

2022-11-29 06:49 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +> Trusted scriptlets rules can be used **only in trusted filters**. This category includes:
Но это ведь справедливо и для обычных скриптлетов или в расширении по-другому?

2022-11-29 08:27 UTC, el-termikael requested changes

2022-11-29 08:27 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +Trusted scriptlets are [scriptlets](#scriptlets) with extended functionality. Their names are prefixed with `trusted-`, e.g `trusted-set-cookie`, to be easily distinguished from common scriptlets.
e.g.

2022-11-29 08:27 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +> * filter lists [created by AdGuard Team](./adguard-filters.md),
by the AdGuard team

2022-11-29 08:27 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +> Trusted scriptlets are not compatible with any other blocker.
Trusted scriptlets are not compatible with other ad blockers except AdGuard.

2022-11-29 10:48 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> Trusted scriptlets rules can be used **only in trusted filters**. This category includes:
справедливо, не по-другому

2022-11-29 10:51 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +> Trusted scriptlets rules can be used **only in trusted filters**. This category includes:
тогда будет логичнее сделать эту заметку где-нибудь [здесь](https://github.com/AdguardTeam/KnowledgeBase/pull/51/files#diff-190ba525f7c4d0b0eda33dab9df98df01d3ac072d6aeef951f044c96d58a25c9R2082)?

2022-11-29 10:57 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +> Trusted scriptlets rules can be used **only in trusted filters**. This category includes:
вообще да. ещё про эти трастед-фильтры много где упоминается и каждый расписано что это значит, резонно описать в одном месте и только ссылаться потом

2022-11-30 10:10 UTC, sxgunchenko approved these changes

2022-12-02 11:37 UTC, el-termikael requested changes

2022-12-02 11:37 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +If you are using AdGuard Browser extension and want to debug a [scriptlet](#scriptlets) or [trusted scriptlet](#trusted-scriptlets) rule, you can get additional information by simply having the Filte
```suggestion
If you are using AdGuard Browser extension and want to debug a [scriptlet](#scriptlets) or a [trusted scriptlet](#trusted-scriptlets) rule, you can get additional information by opening the Filtering log. In that case, scriptlets will switch to debug mode and there will be more information in the browser console.
```

2022-12-02 11:37 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +> Trusted scriptlets rules are supported now by AdGuard for Windows, Mac, and Android, **running CoreLibs version 1.10.141 or later**.
Now trusted scriptlets rules are supported или Trusted scriptlets rules are now supported

2022-12-02 12:33 UTC, el-termikael approved these changes

2022-12-02 12:53 UTC, merged