Update browsing security article
AdguardTeam/KnowledgeBase pull request #521
Opened 2024-06-28 11:02 UTC by SeverAnna

Changed the title, changed most of the info, changed the screenshots

2024-06-28 12:53 UTC, ameshkov commented on docs/general/browsing-security.md
> +![Access blocked by AdGuard](https://cdn.adtidy.org/content/kb/ad_blocker/general/phishing_warning.png)
Let's find the new version of this page

2024-06-28 13:27 UTC, SeverAnna commented on docs/general/browsing-security.md
> +![Access blocked by AdGuard](https://cdn.adtidy.org/content/kb/ad_blocker/general/phishing_warning.png)
спросила дизайнеров, у них нет таких макетов :(

2024-06-28 15:16 UTC, SeverAnna commented on docs/general/browsing-security.md
> +![Access blocked by AdGuard](https://cdn.adtidy.org/content/kb/ad_blocker/general/phishing_warning.png)
поменяла на красивый днсный

2024-06-28 15:45 UTC, ameshkov approved these changes

2024-06-28 17:19 UTC, vbagirov requested changes

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +AdGuard provides the best possible protection by inspecting both the pages and all objects loaded on them. AdGuard checks URLs and domain names using hash prefixes, not the full URLs, so our servers
сказать бы явно в первом предложении что адгард в принципе сверяется с некой базой на сервере, а то только косвенно это понятно

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +::: Important
такого адмонишена вроде нет, здесь перечислены все:
https://docusaurus.io/docs/next/markdown-features/admonitions

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +![Browsing security in Android](https://cdn.adtidy.org/content/kb/ad_blocker/general/bs_android.png?mw=900&mh=600)
тут точно надо mw и mh? да и *mobile наверное надо добавить

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +![Security in iOS](https://cdn.adtidy.org/content/kb/ad_blocker/general/bs_ios.jpg?mw=900&mh=600)
аналогично комменту про андроид

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +- **For iOS**: Although there’s no separate module, you can go to *Safari protection* → *Filters* → *Security* and enable the available filters. Additionally, enable *DNS protection* and select a sui
я бы уточнил что такое suitable

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +- **For AdGuard DNS:** Enable malware protection in *Server settings* under *Security*
уточнить что речь про Private AdGuard DNS

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +## What do we block
What we block правильно, если без вопроса

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +We maintain two primary filters: one that protects against phishing and fraudulent websites aiming to steal user credentials, and another that blocks access to websites known to distribute malware, w
мне кажется лучше написать
and fraudulent websites aimed at stealing user credentials

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +We maintain two primary filters: one that protects against phishing and fraudulent websites aiming to steal user credentials, and another that blocks access to websites known to distribute malware, w
These filters also cover various scams and fraudulent schemes. — не нравится, фильтры всё же "покрывают" сайты, а не скамы и схемы. Я считаю надо переформулировать

2024-06-28 17:19 UTC, vbagirov commented on docs/general/browsing-security.md
> +## If you suspicious about a website
If you are suspicious about a website

2024-07-04 12:54 UTC, vbagirov approved these changes

2024-07-04 13:20 UTC, merged