Describe `$inline-script` and `$inline-font`, add "local" TOCs for modifiers sections
AdguardTeam/KnowledgeBase pull request #53
Opened 2022-11-29 19:25 UTC by slavaleleka

https://github.com/AdguardTeam/KnowledgeBase/issues/49

2022-11-29 19:38 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +#### **`$domain`** {#domain-modifier}
попытался немного выровнять ситуацию
https://uploads.adguard.org/slbdzdrv1zojq.png

2022-11-29 19:40 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +#### **`$app`** {#non-basic-app-modifier}
и здесь чтобы выровнять размер + чтобы из общего содержания убрать потому что выбиваются
https://uploads.adguard.org/slbdzdrvx6ifl.png

2022-11-30 10:14 UTC, sxgunchenko requested changes

2022-11-30 10:14 UTC, sxgunchenko commented on docs/general/ad-filtering/create-own-filters.md
> +* `@@||example.org^$specifichide` — will disable `example.org##.banner` but not `##.banner`.
```suggestion
* `@@||example.org^$specifichide` disables `example.org##.banner` but not `##.banner`.
```

2022-11-30 11:09 UTC, sxgunchenko approved these changes

2022-12-01 18:25 UTC, ameshkov approved these changes

2022-12-02 12:06 UTC, el-termikael requested changes

2022-12-02 12:06 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +`$inline-script` modifier is sort of shortcut for [`$csp`](#csp-modifier) modifier with specific value. E.g. rule `||example.org^$inline-script` is converting into such rule:
```suggestion
`$inline-script` modifier is a sort of a shortcut for [`$csp`](#csp-modifier) modifier with specific value. E.g. the rule `||example.org^$inline-script` is converting into such a rule:
```

2022-12-02 12:06 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
> +`$inline-font` modifier is sort of shortcut for [`$csp`](#csp-modifier) modifier with specific value. E.g. rule `||example.org^$inline-font` is converting into such rule:
```suggestion
`$inline-font` modifier is a sort of a shortcut for [`$csp`](#csp-modifier) modifier with specific value. E.g. the rule `||example.org^$inline-font` is converting into such a rule:
```

2022-12-02 12:21 UTC, el-termikael approved these changes

2022-12-02 12:29 UTC, merged