Update background work for miui 13+ and hyperos.md
AdguardTeam/KnowledgeBase pull request #541
Opened 2024-08-05 11:23 UTC by DashaBu

2024-08-06 13:08 UTC, el-termikael requested changes

2024-08-07 09:17 UTC, el-termikael approved these changes

2024-08-08 09:29 UTC, el-termikael commented on docs/adguard-for-android/solving-problems/background-work.md
> +Depending on the MIUI and HyperOS version there are two ways to change the battery optimization settings on your phone and block ads more efficiently. You can choose one of the following options.
```suggestion
Depending on the MIUI and HyperOS versions, there are two ways to change the battery optimization settings on your phone and block ads more efficiently. You can choose one of the following options.

2024-08-08 09:38 UTC, Versty approved these changes

2024-08-08 09:55 UTC, merged