[Issue #565] Add more information about inspecting the original certificate
AdguardTeam/KnowledgeBase pull request #567
Opened 2024-09-12 17:02 UTC by puglieri

2024-09-16 09:50 UTC, el-termikael requested changes

2024-09-16 09:50 UTC, el-termikael commented on docs/general/https-filtering/known-issues.md
> +- By visiting the section *Recent activity* on AdGuard for Android or *Filtering log* on AdGuard for Windows and AdGuard for Mac. While in the Browser Assistant you can only see the certificate of th
```suggestion
- By visiting the *Recent activity* section in AdGuard for Android or the *Filtering log* section in AdGuard for Windows and AdGuard for Mac. While in the Browser Assistant you can only see the certificate of the website, in Recent activity you can inspect the certificate of any server used in a subrequest or browser, with or without the Browser Assistant. To view the certificate using this method, follow the instructions below.

2024-09-16 09:50 UTC, el-termikael commented on docs/general/https-filtering/known-issues.md
> +On AdGuard for Android:
In — here and below

2024-09-16 09:50 UTC, el-termikael commented on docs/general/https-filtering/known-issues.md
> +3. Under the section *TLS*, click *View website certificate*.
```suggestion
3. Under the *TLS* section, click *View website certificate*.

2024-09-16 09:50 UTC, el-termikael commented on docs/general/https-filtering/known-issues.md
> +1. Click the gear icon. On the dropdown menu, go to *Advanced* → *Filtering log...*.
```suggestion
1. Click the gear icon. In the drop-down menu, go to *Advanced* → *Filtering log...*.

2024-09-16 17:31 UTC, ameshkov requested changes

2024-09-17 13:46 UTC, ameshkov requested changes

2024-09-17 13:46 UTC, ameshkov commented on docs/general/https-filtering/known-issues.md
> +- By using our [Browser Assistant](https://adguard.com/adguard-assistant/overview.html). This browser extension helps you manage filtering directly from the browser and allows you to inspect the orig
No change in the formatting yet (the image is a nested item here).

2024-09-17 13:47 UTC, ameshkov commented
Other [than this](https://github.com/AdguardTeam/KnowledgeBase/pull/567#discussion_r1761567299) everything else is good

2024-09-20 07:57 UTC, el-termikael approved these changes

2024-10-14 11:19 UTC, ameshkov approved these changes

2024-10-14 12:27 UTC, merged