Fix few mv3 articles
AdguardTeam/KnowledgeBase pull request #573
Opened 2024-09-17 14:51 UTC by slavaleleka

2024-09-17 15:57 UTC, el-termikael requested changes

2024-09-17 15:57 UTC, el-termikael commented on docs/adguard-browser-extension/mv3-version.md
> +As MV2 extensions are being phased out in the Chrome Web Store, Chrome users may need to switch to MV3 extensions that are compatible with Chrome's new API Manifest V3. Our thoughts on this topic are
а почему заменил на такие апострофы? по редполитике мы используем `’`

2024-09-17 15:57 UTC, el-termikael commented on docs/adguard-browser-extension/mv3-version.md
> +    Due to DNR restrictions, we can't show exactly which rule worked, but we will provide an "assumed rule that was triggered" based on our engine. For precise information, you'll need to install the
и про кавычки то же самое

2024-09-17 16:29 UTC, slavaleleka commented on docs/adguard-browser-extension/mv3-version.md
> +As MV2 extensions are being phased out in the Chrome Web Store, Chrome users may need to switch to MV3 extensions that are compatible with Chrome's new API Manifest V3. Our thoughts on this topic are
понял, вернул

2024-09-18 05:53 UTC, SeverAnna approved these changes

2024-09-18 07:13 UTC, el-termikael approved these changes

2024-09-18 09:32 UTC, merged