Update installation.md
AdguardTeam/KnowledgeBase pull request #586
Opened 2024-09-27 13:44 UTC by puglieri

2024-10-01 15:36 UTC, el-termikael requested changes

2024-10-01 15:36 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +Besides running the advanced uninstaller in its user-interactive mode, you can also use comand line arguments to uninstall AdGuard for Windows, as listed below:
```suggestion
Besides running the advanced uninstaller in its user-interactive mode, you can also use command-line arguments to uninstall AdGuard for Windows, as listed below:
```

2024-10-01 15:36 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +- `/console` runs Uninstaller in console mode, without the interactive UI. All the command-line parameters below will be ignored if the `/console` mode is not activated
```suggestion
- `/console` runs the uninstaller in console mode, without the interactive UI. All the command-line parameters below will be ignored if the `/console` mode is not activated
```

2024-10-01 15:36 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +- `/adblocker` runs the Uninstaller to uninstall AdGuard for Windows
```suggestion
- `/adblocker` runs the uninstaller to uninstall AdGuard for Windows
```

2024-10-01 15:36 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +- `/advanced` forces the Uninstaller to run in *Advanced mode*
```suggestion
- `/advanced` forces the uninstaller to run in *Advanced mode*
```

2024-10-01 15:36 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +- `/settings` forces the Uninstaller to remove user settings along with the application
```suggestion
- `/settings` forces the uninstaller to remove user settings along with the application
```

2024-10-02 12:58 UTC, adbuker requested changes

2024-10-02 12:58 UTC, adbuker commented on docs/adguard-for-windows/installation.md
> +- `/advanced` forces the uninstaller to run in *Advanced mode*
впн пропустили - https://uploads.adguard.org/buker-few21.png

2024-10-02 12:59 UTC, adbuker commented on docs/adguard-for-windows/installation.md
> +- `/advanced` forces the uninstaller to run in *Advanced mode*
а не, понял, не пропустили. Ну в таком случае странно указывать тут опцию, когда мы удаляем только `/adblocker`. Тогда стоит написать, что **надо** указать этот параметр

2024-10-04 14:51 UTC, el-termikael requested changes

2024-10-04 14:51 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +1. Open the Command prompt by typing *cmd* on the start menu.
```suggestion
1. Open Command Prompt by typing *cmd* from the Start menu.
```

2024-10-04 14:51 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +Besides running the advanced uninstaller in its user-interactive mode, you can also use command-line arguments to uninstall AdGuard for Windows. To do this, follow the instruction below:
```suggestion
Besides running the advanced uninstaller in its user-interactive mode, you can also use command-line arguments to uninstall AdGuard for Windows. To do this, follow the instructions below:
```

2024-10-04 14:51 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +2. On the Command prompt, use `/console` to run the uninstaller in console mode, without the interactive UI. All the command-line parameters below will be ignored if the `/console` mode is not activa
```suggestion
2. Use `/console` to run the uninstaller in console mode, without the interactive UI. All the command-line parameters below will be ignored if the `/console` mode is not activated.
```

2024-10-04 14:51 UTC, el-termikael commented on docs/adguard-for-windows/installation.md
> +4. You can also use `/advanced` to force the uninstaller to run in *Advanced mode*, and `/settings` to force the uninstaller to remove user settings along with the application.
```suggestion
4. You can also use `/advanced` to force the uninstaller to run in *Advanced mode* and `/settings` to force the uninstaller to remove user settings along with the application.
```

2024-10-08 08:20 UTC, el-termikael approved these changes

2024-10-17 11:47 UTC, adbuker commented on docs/adguard-for-windows/installation.md
> +3. Use `/adblocker` to uninstall AdGuard for Windows.
1. надо указать, что параметры /console /adbloker обязательные, иначе адблокер не удалится. Или вообще указать, что поскольку удалятор универсальный необходимо указать продукт явно. А параметры в п.4 опциональны, они повлияют на детали работы
2. ещё здорово будет привести пример 
```
Adguard.UninstallUtility.exe /console /adblocker
```

2024-10-22 11:38 UTC, adbuker approved these changes

2024-10-22 14:03 UTC, merged