Add link to locales dropdown
AdguardTeam/KnowledgeBase pull request #60
Opened 2022-12-08 16:17 UTC by EugeneMeg

2022-12-08 16:20 UTC, ameshkov requested changes
Используй relative ссылки

2022-12-09 11:57 UTC, EugeneMeg commented
Возникла проблема: не получается локализовать `label: 'Help Us Translate'`
При генерации переводов командой _write-translations_ перевод для этого поля не генерится, так как оно находится в элементе массива dropdownItemsAfter. Вариантов решения проблемы найдено не было.

2022-12-13 16:29 UTC, ameshkov approved these changes

2022-12-15 10:20 UTC, ameshkov approved these changes

2022-12-15 10:35 UTC, merged