[GH-issue-594] Add new section to how-ad-blocking-works.md
AdguardTeam/KnowledgeBase pull request #613
Opened 2024-11-25 09:20 UTC by vyanovsky

Added a new section "Types of request handling in AdGuard" to how-ad-blocking-works.md, that explains those types (blocked, allowed, modified) with some examples.

2024-11-25 14:26 UTC, el-termikael requested changes

2024-11-25 14:26 UTC, el-termikael commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +A detailed information about how each request was handled by your AdGuard can be found in the *Filtering log* (AdGuard for Windows, AdGuard for Mac, AdGuard Browser extension) or *Recent activity* (A
```suggestion
Detailed information on how each request of yours has been handled by AdGuard can be found in the *Filtering log* (AdGuard for Windows, AdGuard for Mac, AdGuard Browser Extension) or *Recent activity* (AdGuard for iOS, AdGuard for Android).
```

2024-11-25 14:26 UTC, el-termikael commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +### Blocked requests examples
```suggestion
### Examples of blocked requests
```

2024-11-25 14:26 UTC, el-termikael commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +Filter unblocking search ads and self-promotion allows search ads requests, such as `www.google.com/aclk?`.
search ads requests звучит непонятно — запросы от поисковой рекламы или к ней?
и лишняя запятая перед suсh as

2024-11-25 14:26 UTC, el-termikael commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +Requests to websites that are added by the user to *Allowlist* are allowed.
а это кажется очевидным

2024-11-25 14:26 UTC, el-termikael commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +### Allowed requests examples
```suggestion
### Examples of allowed requests
```

2024-11-25 14:26 UTC, el-termikael commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +### Modified requests examples
```suggestion
### Examples of modified requests
```

2024-11-25 14:26 UTC, el-termikael commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +Please note that *Modified* events you see in the Filtering log or Recent activity do not refer only to the cases when a request is modified, but also when:
```suggestion
Please note that *modified* events you see in the Filtering log or Recent activity refer not only to the cases when a request is modified, but also when:
```

2024-11-26 09:02 UTC, vyanovsky commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +Requests to websites that are added by the user to *Allowlist* are allowed.
ну да, но я бы оставил с той точки зрения что в целом этот текстик это как бы документация на минималках, то есть здесь there's no such thing as too obvious и кмк нет необходимости сокращать так же как в тексте для более казуального чтения, а фактически это корректный пример таких риквестов

2024-11-26 09:09 UTC, vyanovsky commented on docs/general/ad-filtering/how-ad-blocking-works.md
> +Filter unblocking search ads and self-promotion allows search ads requests, such as `www.google.com/aclk?`.
подправил

2024-11-26 10:43 UTC, el-termikael approved these changes

2024-11-27 08:35 UTC, merged