[AG-38479] Updated userscript development section in extensions article
AdguardTeam/KnowledgeBase pull request #632
Opened 2024-12-23 12:42 UTC by kurrx

2024-12-23 13:49 UTC, el-termikael requested changes

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +[Here](https://wiki.greasespot.net/Greasemonkey_Manual:API) you can find more information about Greasemonkey API.
```suggestion
You can find more information about Greasemonkey API in [its manual](https://wiki.greasespot.net/Greasemonkey_Manual:API) .
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +#### Trusted Types Policy API
нашла TrustedTypePolicy (https://developer.mozilla.org/en-US/docs/Web/API/TrustedTypePolicy) и Trusted Types API (https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API)

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +AdGuard provides an instance of `PolicyApi` class that allows you to manage Trusted Types in your userscripts.
```suggestion
AdGuard provides an instance of the `PolicyApi` class that allows you to manage Trusted Types in your userscripts.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +You can access instance of this class by using `ADG_policyApi` variable in your userscript.
```suggestion
You can access the instance of this class by using the `ADG_policyApi` variable in your userscript.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +- `isSupported: boolean` - Flag that indicates is Trusted Types API supported or not in the current browser.
```suggestion
- `isSupported: boolean` — a flag indicating whether or not the Trusted Types API is supported by the current browser.

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +- [`ADG_policyApi.createHTML`]. If not supported returns `input: string` back.
```suggestion
- [`ADG_policyApi.createHTML`]. If not supported, returns `input: string`.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +- [`ADG_policyApi.createHTML`]. If not supported returns `input: string` back.
ниже аналогично

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +[`ADG_policyApi.createHTML`]: https://developer.mozilla.org/en-US/docs/Web/API/TrustedTypePolicy/createHTML
```suggestion
[`ADG_policyApi.createHTML`](https://developer.mozilla.org/en-US/docs/Web/API/TrustedTypePolicy/createHTML)
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +[`ADG_policyApi.createHTML`]: https://developer.mozilla.org/en-US/docs/Web/API/TrustedTypePolicy/createHTML
мб в таком формате?

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * Enum representation of return values of `getAttributeType` and
```suggestion
 * Enum representation of the return values of the `getAttributeType` and
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * `getPropertyType` methods of native Trusted Types API.
```suggestion
 * `getPropertyType` methods of the native Trusted Types API.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * Isomorphic trusted value type, if browser supports Trusted Types API it will be one of the
```suggestion
 * Isomorphic trusted value type. If a browser supports the Trusted Types API, it will be one of the enum Trusted Types
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * `TrustedHTML`, `TrustedScript` or `TrustedScriptURL`, otherwise it will be regular `string`.
```suggestion
 * (`TrustedHTML`, `TrustedScript` or `TrustedScriptURL`); otherwise, it will be regular `string`.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * - or returns back `value` if none of them applicable.
```suggestion
 * - or returns `value` if none of them is applicable.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * @param type Trusted Type.
```suggestion
 * @param type — Trusted Type.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * @param type Trusted Type.
ниже аналогично

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * @param value Value from which creates Trusted Type.
```suggestion
 * @param value — a value from which a Trusted Type is created.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> +- `name: string` - Name of the policy (Default is `"AGPolicy"`).
```suggestion
- `name: string` — a name of the policy (Default is `"AGPolicy"`).
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * Creates Trusted Type depending on `type`:
```suggestion
 * Creates a Trusted Type depending on `type`:
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * - or returns back `value` if none of them applicable.
```suggestion
 * - or returns `value` if none of them applicable.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * - or returns back `value` if none of them applicable.
```suggestion
 * - or returns `value` if none of them is applicable.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * @param property Property.
```suggestion
 * @param property — a property.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * @param value Value or property.
```suggestion
 * @param value — a value or a property.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * @param elementNS Element namespace, if empty defaults to the HTML namespace.
```suggestion
 * @param elementNS — an element namespace. If empty, defaults to the HTML namespace.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * @param createArgs Additional arguments to be passed to the function represented by `TrustedTypePolicy`.
```suggestion
 * @param createArgs — additional arguments to be passed to the function represented by `TrustedTypePolicy`.
```

2024-12-23 13:49 UTC, el-termikael commented on docs/general/extensions.md
> + * @returns Converted value.
```suggestion
 * @returns — a converted value.
```

2024-12-24 07:36 UTC, kurrx commented on docs/general/extensions.md
> + * @param type Trusted Type.
Зарезолвил похожие саджешн тк это jsdoc и тут не используется "-" и не начинаем с артикля

2024-12-24 07:42 UTC, kurrx commented on docs/general/extensions.md
> +#### Trusted Types Policy API
Переименовал в `Trusted Types API`

2024-12-24 08:23 UTC, ameshkov approved these changes

2024-12-24 08:26 UTC, el-termikael commented on docs/general/extensions.md
>   * @returns Converted value.
```suggestion
 * @returns — a converted value.
```

2024-12-24 08:59 UTC, maximtop approved these changes

2024-12-24 11:43 UTC, kurrx commented on docs/general/extensions.md
> + * @param value Value of an attribute to be converted.
Это документация внутри кода, тут думаю "-" и артикли не нужны.
Все таски ниже резолвлю тоже

2024-12-24 12:01 UTC, el-termikael approved these changes

2024-12-25 08:44 UTC, ameshkov approved these changes

2024-12-26 10:04 UTC, slavaleleka approved these changes

2025-01-13 08:57 UTC, el-termikael approved these changes

2025-01-13 09:14 UTC, merged