minor fixes: updated text formatting and added links
AdguardTeam/KnowledgeBase pull request #69
Opened 2022-12-20 12:30 UTC by anastasiia-fedotova

2022-12-20 12:51 UTC, vbagirov requested changes

2022-12-20 12:51 UTC, vbagirov commented on docs/adguard-for-windows/solving-problems/system-logs.md
> +Please send the two files that you've recently saved to the AdGuard support service at *support@adguard.com*.
мне кажется лучше жирным оставить, это же не кнопка. Ну или вообще ссылку на статью кб про техсаппорт

2022-12-22 07:23 UTC, el-termikael requested changes

2022-12-22 07:23 UTC, el-termikael commented on docs/adguard-for-windows/overview.md
> +This is the main module of AdGuard for Windows that removes ads from the websites you visit and from the apps installed on your device. To filter out advertising and privacy-threatening content such
./general/ad-filtering/how-ad-blocking-works, @slavaleleka да же?

2022-12-22 07:23 UTC, el-termikael commented on docs/adguard-for-windows/solving-problems/system-logs.md
> +Please send the two files that you've recently saved to the [AdGuard support service](/support/contact).
я убрала вкладку про саппорт, замени на to support@adguard.com

2022-12-22 09:44 UTC, slavaleleka commented on docs/adguard-for-windows/overview.md
> +This is the main module of AdGuard for Windows that removes ads from the websites you visit and from the apps installed on your device. To filter out advertising and privacy-threatening content such
`../../general/ad-filtering/how-ad-blocking-works`

2022-12-22 14:06 UTC, vbagirov requested changes

2022-12-22 14:06 UTC, vbagirov commented on docs/adguard-for-windows/overview.md
> +This is the main module of AdGuard for Windows that removes ads from the websites you visit and from the apps installed on your device. To filter out advertising and privacy-threatening content such
там, где у тебя ссылка идёт от корня, можно просто писать `/general/......` или `/adguard-for-windows/......` и т.д., не обязательно вести туда переходами через всякие `../..`

2022-12-22 14:06 UTC, vbagirov commented on docs/adguard-for-windows/overview.md
> +![Parental Control](https://cdn.adguard.com/content/kb/ad_blocker/windows/overview/parental-control.png)
`cdn.adtidy.org`

2022-12-26 09:38 UTC, vbagirov approved these changes

2022-12-26 10:02 UTC, el-termikael approved these changes

2022-12-26 10:06 UTC, merged