Update intro article
AdguardTeam/KnowledgeBase pull request #7
Opened 2022-07-27 13:46 UTC by vbagirov

2022-07-27 14:27 UTC, el-termikael requested changes

2022-07-27 14:27 UTC, el-termikael commented on docs/intro.md
> +## What is AdGuard Ad Blocker
What AdGuard Ad Blocker is / What is AdGuard Ad Blocker?

2022-07-27 14:27 UTC, el-termikael commented on docs/intro.md
> +AdGuard is one of the leaders on the market of ad blocking software with 10+ years of experience, almost a dozen products for various platforms, and over 30 million user installs. Unlike other ad blo
```suggestion
AdGuard is one of the leaders on the market of ad-blocking software with 10+ years of experience, almost a dozen products for various platforms, and 30+ million users. Unlike other ad-blocking solutions, most of which are browser-based, we offer standalone apps for all major platforms, both desktop and mobile ones. Apps are more powerful than browser extensions, can block more and do it more efficiently:
```

2022-07-27 14:27 UTC, el-termikael commented on docs/intro.md
> +[AdGuard Browser extension for Chromium, Firefox, Edge](placeholder-link)
Chrome?

2022-07-27 15:18 UTC, vbagirov commented on docs/intro.md
> +[AdGuard Browser extension for Chromium, Firefox, Edge](placeholder-link)
Не только Chrome, но и другие браузеры на основе хрома типа Оперы

2022-07-27 15:18 UTC, vbagirov commented on docs/intro.md
> +AdGuard is one of the leaders on the market of ad blocking software with 10+ years of experience, almost a dozen products for various platforms, and over 30 million user installs. Unlike other ad blo
там именно установки, кажется

2022-07-27 15:47 UTC, el-termikael commented on docs/intro.md
> +[AdGuard Browser extension for Chromium, Firefox, Edge](placeholder-link)
тогда я бы написала Chromium-based browsers

2022-07-28 07:37 UTC, el-termikael approved these changes

2022-07-28 07:38 UTC, merged