Update activation instructions
AdguardTeam/KnowledgeBase pull request #71
Opened 2022-12-20 14:56 UTC by vyanovsky

Adding refreshed step-by-step activation instructions for each platform to activation.md

2022-12-20 15:15 UTC, el-termikael requested changes

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +To activate your license, go to the *License* section of your AdGuard product and find the *Log in* field or *Activate* button. Then use the email and password of your AdGuard account to log in. If y
я бы написала просто Use the email and password of your AdGuard account to log in

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +> Note: For successful activation using AdGuard account, you need to have a valid license with at least one open slot there. (If your license is already used on a maximum number of devices, you can [
```suggestion
> Note: To activate a license via AdGuard account, you need to have a valid license with at least one open slot there. If your license is already used on a maximum number of devices, you can [upgrade it](#how-to-upgrade-a-license) or [transfer it from one device to another](#how-to-transfer-a-license-to-another-device).
```

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +To do it, doubleclick on the AdGuard icon on the desktop:
double-click the AdGuard icon

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +or double click on the AdGuard icon in the system tray:
double-click the AdGuard icon in the system tray menu

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +2. Go to **License** in the main menu, then click **Activate license**
```suggestion
2. Go to **License** tab in the app menu and click **Activate license**
```

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +- Via entering **Email** and **Password** from your **AdGuard  account** (or through a FB/Google/Apple account)
```suggestion
 Via entering the email and password from your **AdGuard  account** (or from your Facebook, Google, or Apple account)
```

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +1. Open AdGuard app (lick on the AdGuard icon in the menu bar)
```suggestion
1. Open the AdGuard app (click the AdGuard icon in the menu bar)
```

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +2. Click on **gear icon** in the top right corner
```suggestion
2. Click the **gear icon** in the top right corner
```

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +4. In the opened window press **Activate** button
press **Activate** / press the **Activate** button

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +- Activate by entering **Email** and **Password** from your **AdGuard  account** (or through a FB/Google/Apple account)
Via entering the email and password from your **AdGuard  account** (or from your Facebook, Google, or Apple account)

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +- Activate with a **license key**
Via entering the **license key**

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +4. Tap **three dots menu (⋮)** in the top right corner of the screen
three-dot menu

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +![Tap three dot menu](https://cdn.adguard.com/public/Adguard/kb/newscreenshots/En/General/android2En.png)
three-dot

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +- Enter **Email** and **Password** from your **AdGuard account** (or sign in with Facebook/Google account)
Via entering the email and password from your AdGuard account (or from your Facebook, Google, or Apple account)

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +- Or enter a **license key**
Via entering the **license key**

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +1. Open the application and tap on the **gear icon** in the bottom right corner of the screen
```suggestion
1. Open the AdGuard app and tap the **gear icon** in the bottom right corner of the screen
```

2022-12-20 15:15 UTC, el-termikael commented on docs/general/license/activation.md
> +4. Enter **Email** and **Password** from your **AdGuard account**
зачем с больших?

2022-12-20 16:20 UTC, vyanovsky commented on docs/general/license/activation.md
> +4. Enter **Email** and **Password** from your **AdGuard account**
не знаю, так в старой инструкции было. ну вообще названия полей так выглядят (с большой), поэтому так легче мб просто визуально увидеть что надо заполнять. это как названия полей с которыми юзер должен взаимодействовать

2022-12-20 16:21 UTC, vyanovsky commented on docs/general/license/activation.md
> +- Or enter a **license key**
не уверен что the, мы же не про какой-то конкретный ключ говорим

2022-12-20 16:23 UTC, vyanovsky commented on docs/general/license/activation.md
> +![Tap three dot menu](https://cdn.adguard.com/public/Adguard/kb/newscreenshots/En/General/android2En.png)
в гугле и так и так пишут, я оттуда взял

2022-12-20 16:23 UTC, vyanovsky commented on docs/general/license/activation.md
> +- Activate with a **license key**
*не уверен что the, мы же не про какой-то конкретный ключ говорим

2022-12-20 16:30 UTC, el-termikael commented on docs/general/license/activation.md
> +- Or enter a **license key**
тогда здесь тоже поправь на a: https://uploads.adguard.org/el.termikael9tx32.png

2022-12-20 16:30 UTC, el-termikael commented on docs/general/license/activation.md
> +4. Enter **Email** and **Password** from your **AdGuard account**
ну хз насколько легче...

2022-12-21 14:03 UTC, el-termikael requested changes

2022-12-21 14:03 UTC, el-termikael commented on docs/general/license/activation.md
> +- Via entering the **email** and **password** from your **AdGuard  account** (or through a FB/Google/Apple account)
AdGuard account (лишний пробел) + осталось `a FB/Google/Apple account`, так не очень

2022-12-21 14:03 UTC, el-termikael commented on docs/general/license/activation.md
> +- Activate by entering **Email** and **Password** from your **AdGuard  account** (or through a FB/Google/Apple account)
и тут

2022-12-21 14:03 UTC, el-termikael commented on docs/general/license/activation.md
> +- Activate with a **license key**
ну значит а, но давай везде единообразно. выше было Via entering

2022-12-21 15:47 UTC, el-termikael requested changes

2022-12-21 15:47 UTC, el-termikael commented on docs/general/license/activation.md
> +- Via entering **email** and **password** from your **AdGuard  account** (or from your Facebook/Google/Apple account)
the **email** and **password**

2022-12-21 21:29 UTC, el-termikael approved these changes

2022-12-22 06:34 UTC, merged