Added content for Content Blocker
AdguardTeam/KnowledgeBase pull request #8
Opened 2022-07-27 17:20 UTC by ss-orlova

2022-07-29 16:15 UTC, vbagirov requested changes

2022-07-29 16:15 UTC, vbagirov commented on docs/adguard-content-blocker/features-overview.md
> +AdGuard has two Android apps: [AdGuard for Android](https://adguard.com/en/adguard-android/overview.html) and AdGuard Content Blocker. Whereas AdGuard for Android can be downloaded on AdGuard's offic
тут либо сразу расписать, в чем преимущество АГ для андроида, либо выделить блокквоутом. А то люди прочитают и подумают что контент блокер лучше, раз его можно в гуглплей скачать

2022-07-29 16:15 UTC, vbagirov commented on docs/adguard-content-blocker/features-overview.md
> +Full-fledged ad blockers can’t be introduced in Google Play due to the policy of the store. Google Play [has banned](https://adguard.com/en/blog/google-removes-adguard-android-app-google-play.html) "
introduced to видимо, а не introduced in

2022-07-29 16:15 UTC, vbagirov commented on docs/adguard-content-blocker/features-overview.md
> +2. Within the existing technology, the functionality of AdGuard Content Blocker is limited: for example it cannot block ads and trackers in apps, has no filtering log and doesn't support filtering at
...apps or other browsers

2022-07-29 16:15 UTC, vbagirov commented on docs/adguard-content-blocker/installation.md
> +If you don't have a required browser, you will be prompted to choose and install one.
required -> supported

2022-07-29 16:15 UTC, vbagirov commented on docs/adguard-content-blocker/installation.md
> +If you don't have a required browser, you will be prompted to choose and install one.
и наверное надо добавить "...installed on your device"

2022-07-29 16:15 UTC, vbagirov commented on docs/adguard-content-blocker/installation.md
> +![Onboarding: no required browser](https://cdn.adguard.com/content/Kb/ad_blocker/content_blocker/content_blocker_onboarding3.jpg)
тоже required -> supported

2022-07-29 16:15 UTC, vbagirov commented on docs/adguard-content-blocker/installation.md
> +After the required browser is installed, you can start AdGuard Content Blocker and block ads and trackers there.
After one of the supported ...

2022-07-29 16:27 UTC, Alex-302 commented on docs/adguard-content-blocker/features-overview.md
> +AdGuard has two Android apps: [AdGuard for Android](https://adguard.com/en/adguard-android/overview.html) and AdGuard Content Blocker. Whereas AdGuard for Android can be downloaded on AdGuard's offic
Можно и про недостатки первого написать(поддерживает только самый базовый синтаксис, и многие виды рекламы ему не по зубам)

2022-08-08 11:51 UTC, vbagirov approved these changes

2022-08-08 11:52 UTC, merged