Extend `$jsonprune` modifier documentation
AdguardTeam/KnowledgeBase pull request #97
Opened 2022-12-22 17:31 UTC by ngorskikh

2022-12-22 17:36 UTC, Alex-302 commented
Может соотв. пример JSON добавить?

2022-12-22 17:39 UTC, slavaleleka requested changes

2022-12-22 17:39 UTC, slavaleleka commented on i18n/ru/docusaurus-plugin-content-docs/current/general/ad-filtering/create-own-filters.md
> +**Вложенные JSONPath-выражения**
`ru` надо править

2022-12-22 18:50 UTC, ngorskikh commented on i18n/ru/docusaurus-plugin-content-docs/current/general/ad-filtering/create-own-filters.md
> +**Вложенные JSONPath-выражения**
Ну я сэкономил время переводчикам, зачем теперь удалять :)

2022-12-22 19:38 UTC, Alex-302 commented
Вот про примеры жсонов задача
https://github.com/AdguardTeam/KnowledgeBase/issues/91
можно в этом же сделать наверное.

2022-12-22 19:42 UTC, slavaleleka commented on i18n/ru/docusaurus-plugin-content-docs/current/general/ad-filtering/create-own-filters.md
> +**Вложенные JSONPath-выражения**
переводить надо в краудине.

2022-12-23 11:57 UTC, ngorskikh commented
@Alex-302 :sdelal:

2022-12-25 22:07 UTC, el-termikael requested changes

2022-12-25 22:07 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
>  * `||example.org^$jsonprune=\$.elems[?(has "\$.a.b.c")]` – remove all children of `elems` which have a property selectable by the JSONPath expression `$.a.b.c`.
* `||example.org^$jsonprune=\$.elems[?(has "\$.a.b.c")]` removes all children of `elems` which have a property selectable by the JSONPath expression `$.a.b.c`.

2022-12-25 22:07 UTC, el-termikael commented on docs/general/ad-filtering/create-own-filters.md
>  * `||example.org^$jsonprune=\$.elems[?(key-eq "\$.a.b.c" "abc")]` – remove all children of `elems` which have a property selectable by the JSONPath expression `$.a.b.c` with a value equal to `"abc"`.
* `||example.org^$jsonprune=\$.elems[?(key-eq "\$.a.b.c" "abc")]` removes all children of `elems` which have a property selectable by the JSONPath expression `$.a.b.c` with a value equal to `"abc"`.

2022-12-26 13:03 UTC, slavaleleka commented on docs/general/ad-filtering/create-own-filters.md
> +</details>
внутри примера осталось
https://uploads.adguard.org/slbdzdrv5nhdw.png

2022-12-30 11:32 UTC, el-termikael approved these changes

2022-12-30 13:01 UTC, ameshkov approved these changes

2022-12-30 14:34 UTC, ngorskikh commented
@slavaleleka Нужна галочка от тебя :harold:

2022-12-30 14:35 UTC, slavaleleka approved these changes

2022-12-30 14:39 UTC, merged